/* Copyright(C) 2024-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * components.test.ts: Unit tests for the reusable HTML component generators in components.ts. The exports are pure string-building functions (alerts, buttons,
 * badges, status indicators, text inputs, selects, sections, panel headers). Tests focus on output structure, attribute presence/absence, HTML escaping of
 * user-provided text, and the optional-flag fork in each generator. The wizard modal generator lives in components.wizard.test.ts to keep both files under
 * the per-file LOC cap.
 */
import { describe, test } from "node:test";
import { generateAlert, generateBadge, generateButton, generatePanelHeader, generateSection, generateSelect, generateSimpleAlert, generateStatusIndicator,
  generateTextInput } from "./components.ts";
import assert from "node:assert/strict";

describe("generateAlert", () => {

  test("emits an alert div with class alert-<type> and a title block", () => {

    const html = generateAlert("success", "All Set", "Operation complete.");

    assert.match(html, /<div class="alert alert-success">/, "should open with the typed alert div");
    assert.match(html, /<div class="alert-title">All Set<\/div>/, "should include the title block");
    assert.match(html, /Operation complete\./, "should include the message body");
    assert.match(html, /<\/div>$/, "should close the div");
  });

  test("escapes HTML in the title", () => {

    // Negative test: malicious or accidental HTML in the title must be rendered as text, not executed.
    const html = generateAlert("error", "<script>alert('x')</script>", "msg");

    assert.match(html, /&lt;script&gt;/);
    assert.doesNotMatch(html, /<script>alert\('x'\)<\/script>/);
  });

  test("escapes the message by default", () => {

    const html = generateAlert("warning", "title", "<b>raw</b>");

    assert.match(html, /&lt;b&gt;raw&lt;\/b&gt;/);
  });

  test("does not escape the message when escapeMessage=false", () => {

    // Boundary: the optional fourth argument disables message escaping for callers that want to embed pre-rendered HTML (e.g., generated by other component
    // helpers). Locking the contract.
    const html = generateAlert("success", "title", "<b>bold</b>", false);

    assert.match(html, /<b>bold<\/b>/);
  });

  test("supports each documented alert type", () => {

    for(const type of [ "error", "success", "warning" ] as const) {

      const html = generateAlert(type, "t", "m");

      assert.match(html, new RegExp("alert-" + type), "should include alert-" + type);
    }
  });
});

describe("generateSimpleAlert", () => {

  test("emits a single-line alert with the message embedded and escaped", () => {

    const html = generateSimpleAlert("error", "Something went wrong.");

    assert.match(html, /<div class="alert alert-error">Something went wrong\.<\/div>/);
  });

  test("escapes the message", () => {

    const html = generateSimpleAlert("warning", "<i>raw</i>");

    assert.match(html, /&lt;i&gt;raw&lt;\/i&gt;/);
  });
});

describe("generateButton", () => {

  test("emits a button with type, class, and label", () => {

    const html = generateButton("Save", { variant: "primary" });

    assert.match(html, /<button /);
    assert.match(html, /type="button"/);
    assert.match(html, /class="btn btn-primary"/);
    assert.match(html, />Save<\/button>$/);
  });

  test("includes btn-sm when size is sm", () => {

    const html = generateButton("Save", { size: "sm", variant: "primary" });

    assert.match(html, /class="btn btn-primary btn-sm"/);
  });

  test("appends an extra className when provided", () => {

    const html = generateButton("Save", { className: "extra", variant: "primary" });

    assert.match(html, /class="btn btn-primary extra"/);
  });

  test("includes id when provided and escapes it", () => {

    const html = generateButton("Save", { id: "my\"id", variant: "primary" });

    assert.match(html, /id="my&quot;id"/);
  });

  test("includes onclick when provided and escapes it", () => {

    const html = generateButton("Save", { onclick: "alert(\"x\")", variant: "primary" });

    assert.match(html, /onclick="alert\(&quot;x&quot;\)"/);
  });

  test("adds the disabled attribute when disabled=true", () => {

    const html = generateButton("Save", { disabled: true, variant: "primary" });

    assert.match(html, / disabled>/);
  });

  test("omits the disabled attribute when disabled is false or unset", () => {

    // Boundary: explicit false vs. unset both behave the same way (no disabled attribute).
    const a = generateButton("Save", { disabled: false, variant: "primary" });
    const b = generateButton("Save", { variant: "primary" });

    assert.doesNotMatch(a, / disabled>/);
    assert.doesNotMatch(b, / disabled>/);
  });

  test("escapes the label", () => {

    const html = generateButton("<b>x</b>", { variant: "primary" });

    assert.match(html, />&lt;b&gt;x&lt;\/b&gt;<\/button>$/);
  });

  test("supports each documented button variant", () => {

    for(const variant of [ "danger", "delete", "edit", "primary", "secondary" ] as const) {

      const html = generateButton("L", { variant });

      assert.match(html, new RegExp("btn-" + variant));
    }
  });

  test("defaults type to button when unset", () => {

    // Boundary: omitting type produces type="button" rather than HTML's submit default. This matters because most of these buttons are inside forms that should
    // not auto-submit on Enter.
    const html = generateButton("Save", { variant: "primary" });

    assert.match(html, /type="button"/);
  });
});

describe("generateBadge", () => {

  test("emits a span with badge-<variant> class and escaped label", () => {

    const html = generateBadge("Custom", "custom");

    assert.equal(html, "<span class=\"badge badge-custom\">Custom</span>");
  });

  test("escapes the label", () => {

    const html = generateBadge("<b>", "builtin");

    assert.match(html, /&lt;b&gt;/);
  });
});

describe("generateStatusIndicator", () => {

  test("emits a span with status-<status> class, a dot, and the escaped label", () => {

    const html = generateStatusIndicator("healthy", "All systems go");

    assert.match(html, /class="status-indicator status-healthy"/);
    assert.match(html, /class="status-dot"/);
    assert.match(html, /All systems go/);
  });

  test("escapes the status string (defensive)", () => {

    // The status comes from internal code paths but the generator escapes it as defense in depth. We lock the behavior so a future caller that passes
    // user-controlled data is still safe.
    const html = generateStatusIndicator("\"x\"", "label");

    assert.match(html, /status-&quot;x&quot;/);
  });
});

describe("generateTextInput", () => {

  test("renders a labeled text input with id, name, and value", () => {

    const html = generateTextInput("Name", { id: "fld", name: "fld", value: "abc" });

    assert.match(html, /<div class="form-row">/);
    assert.match(html, /<label for="fld">Name<\/label>/);
    assert.match(html, /<input /);
    assert.match(html, /type="text"/);
    assert.match(html, /id="fld"/);
    assert.match(html, /name="fld"/);
    assert.match(html, /value="abc"/);
  });

  test("includes the type attribute when overridden", () => {

    const html = generateTextInput("URL", { id: "u", name: "u", type: "url" });

    assert.match(html, /type="url"/);
  });

  test("uses an empty value when no value is provided", () => {

    const html = generateTextInput("Name", { id: "f", name: "f" });

    assert.match(html, /value=""/);
  });

  test("includes required, disabled, pattern, placeholder, min, max, step attributes when set", () => {

    const html = generateTextInput("Number", {

      disabled: true,
      id: "n",
      max: 100,
      min: 0,
      name: "n",
      pattern: "\\d+",
      placeholder: "Enter",
      required: true,
      step: "1",
      type: "number"
    });

    assert.match(html, / required/);
    assert.match(html, / disabled/);
    assert.match(html, /pattern="\\d\+"/);
    assert.match(html, /placeholder="Enter"/);
    assert.match(html, /min="0"/);
    assert.match(html, /max="100"/);
    assert.match(html, /step="1"/);
  });

  test("omits min/max attributes when they are undefined (boundary)", () => {

    // Boundary: min=0 is a valid number that should still produce min="0". The check is `min !== undefined`, so 0 is included.
    const withZero = generateTextInput("N", { id: "n", min: 0, name: "n" });
    const withoutZero = generateTextInput("N", { id: "n", name: "n" });

    assert.match(withZero, /min="0"/);
    assert.doesNotMatch(withoutZero, /min=/);
  });

  test("appends the hint when provided", () => {

    const html = generateTextInput("Name", { hint: "Helpful hint", id: "f", name: "f" });

    assert.match(html, /<div class="hint">Helpful hint<\/div>/);
  });

  test("escapes the label, value, placeholder, and hint", () => {

    const html = generateTextInput("<L>", { hint: "<H>", id: "f", name: "f", placeholder: "<P>", value: "<V>" });

    assert.match(html, /<label for="f">&lt;L&gt;<\/label>/);
    assert.match(html, /value="&lt;V&gt;"/);
    assert.match(html, /placeholder="&lt;P&gt;"/);
    assert.match(html, /<div class="hint">&lt;H&gt;<\/div>/);
  });
});

describe("generateSelect", () => {

  test("renders a labeled select with options", () => {

    const html = generateSelect("Mode", {

      id: "mode",
      name: "mode",
      options: [
        { label: "Fast", value: "fast" },
        { label: "Safe", selected: true, value: "safe" }
      ]
    });

    assert.match(html, /<label for="mode">Mode<\/label>/);
    assert.match(html, /<select id="mode" name="mode">/);
    assert.match(html, /<option value="fast">Fast<\/option>/);
    assert.match(html, /<option value="safe" selected>Safe<\/option>/);
    assert.match(html, /<\/select>/);
  });

  test("includes the required and disabled attributes when set", () => {

    const html = generateSelect("Mode", {

      disabled: true,
      id: "m",
      name: "m",
      options: [],
      required: true
    });

    assert.match(html, / required/);
    assert.match(html, / disabled/);
  });

  test("appends the hint when provided", () => {

    const html = generateSelect("Mode", { hint: "Pick one", id: "m", name: "m", options: [] });

    assert.match(html, /<div class="hint">Pick one<\/div>/);
  });

  test("escapes option labels and values", () => {

    const html = generateSelect("Mode", {

      id: "m",
      name: "m",
      options: [{ label: "<L>", value: "<V>" }]
    });

    assert.match(html, /<option value="&lt;V&gt;">&lt;L&gt;<\/option>/);
  });

  test("renders an empty select when options is empty (boundary)", () => {

    const html = generateSelect("Mode", { id: "m", name: "m", options: [] });

    assert.match(html, /<select id="m" name="m">/);
    assert.match(html, /<\/select>/);
    assert.doesNotMatch(html, /<option/);
  });
});

describe("generateSection", () => {

  test("wraps content in a div.section without a heading by default", () => {

    const html = generateSection("<p>body</p>");

    assert.match(html, /<div class="section">/);
    assert.match(html, /<p>body<\/p>/);
    assert.doesNotMatch(html, /<h2>/);
    assert.doesNotMatch(html, /<h3>/);
  });

  test("renders the heading at level 3 by default when provided", () => {

    const html = generateSection("body", "Title");

    assert.match(html, /<h3>Title<\/h3>/);
  });

  test("respects an explicit heading level of 2", () => {

    const html = generateSection("body", "Title", 2);

    assert.match(html, /<h2>Title<\/h2>/);
    assert.doesNotMatch(html, /<h3>/);
  });

  test("escapes the heading", () => {

    const html = generateSection("body", "<X>");

    assert.match(html, /<h3>&lt;X&gt;<\/h3>/);
  });
});

describe("generatePanelHeader", () => {

  test("emits a panel header div with an h2 title", () => {

    const html = generatePanelHeader("Title");

    assert.match(html, /<div class="panel-header">/);
    assert.match(html, /<h2>Title<\/h2>/);
    assert.match(html, /<\/div>$/);
  });

  test("appends action HTML verbatim (no escaping)", () => {

    // The action HTML is generated by other component helpers (e.g., generateButton) that already escape user data, so the panel header should pass it through.
    const html = generatePanelHeader("Title", "<button>Add</button>");

    assert.match(html, /<button>Add<\/button>/);
  });

  test("escapes the title (defense in depth)", () => {

    const html = generatePanelHeader("<X>");

    assert.match(html, /<h2>&lt;X&gt;<\/h2>/);
  });
});

