/* Copyright(C) 2024-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * channels.ts: Client-side JavaScript generator for the PrismCast channels subtab.
 */
import { ACTIONS } from "../../clientActions.ts";

/**
 * Generates the channels subtab script block containing the service profile wizard, the browse channels wizard, the tag manager, and the setup wizard, plus the
 * data-click-action registrations that wire server-rendered buttons to these handlers.
 * @returns HTML script block with channels subtab functions.
 */
export function generateChannelsSubtabScript(): string {

  return [
    "<script>",
    "(function() {",

    // Channels subtab switching via the shared factory.
    "  const switchChannelsSubtab = createSubtabSwitcher({",
    "    btnSelector: '.channels-subtab-btn',",
    "    dataAttr: 'data-channels-subtab',",
    "    hashFn: (s) => (s === 'channels') ? '#channels' : '#channels/' + s,",
    "    panelPrefix: 'channels-subtab-',",
    "    panelSelector: '.channels-subtab-panel',",
    "    storageKey: 'prismcast-channels-subtab'",
    "  });",
    "  window.switchChannelsSubtab = switchChannelsSubtab;",

    // Replace the Custom Profiles panel content with server-rendered HTML. Called after profile mutations to update the panel without a page reload.
    // Re-runs processServiceDisplays() so dynamically swapped service icon elements render correctly.
    "  function applyProfilePanel(html) {",
    "    const panel = document.querySelector('#channels-subtab-custom-profiles .section');",
    "    if(panel) {",
    "      panel.innerHTML = html;",
    "      if(window.processServiceDisplays) { processServiceDisplays(); }",
    "    }",
    "  }",

    // Delete a user profile with confirmation.
    "  window.deleteUserProfile = async (key) => {",
    "    if(!confirm('Delete profile \"' + key + '\" and all its domain mappings?')) return;",
    "    try {",
    "      const res = await fetch('/config/profiles/' + encodeURIComponent(key), { method: 'DELETE' });",
    "      const data = await res.json();",
    "      if(data.success) {",
    "        showToast(data.message || 'Profile deleted.', 'success');",
    "        if(data.panelHtml) { applyProfilePanel(data.panelHtml); }",
    "      } else { showToast('Failed to delete profile: ' + extractErrorMessage(data, 'Unknown error.'), 'error'); }",
    "    } catch(err) { console.error('Profile delete request failed.', err); showToast('Failed to delete profile.', 'error'); }",
    "  };",

    // Edit an existing user profile by pre-populating the wizard.
    "  window.editUserProfile = async (key) => {",
    "    try {",
    "      const res = await fetch('/config/profiles');",
    "      const data = await res.json();",
    "      if(!data.success) { showToast('Failed to load profiles.', 'error'); return; }",
    "      const profiles = data.profiles || [];",
    "      const match = profiles.find((p) => p.key === key);",
    "      if(!match || !match.profile) { showToast('Profile not found.', 'error'); return; }",
    "      const p = match.profile;",
    "      const editCs = p.channelSelection || {};",
    "      const strat = editCs.strategy || 'none';",
    "      const strategyFields = {};",
    "      const editStrat = window.__wizardStrategies.find((st) => st.id === strat);",
    "      if(editStrat) {",
    "        for(const ef of editStrat.fields) {",
    "          if(ef.type === 'text' && editCs[ef.id]) { strategyFields[ef.id] = editCs[ef.id]; }",
    "          else if(ef.type === 'boolean' && editCs[ef.id]) { strategyFields[ef.id] = true; }",
    "        }",
    "      }",
    // Rehydrate the rendered profile fields from the registry: boolean flags into flags, text selectors into fieldValues. This is truthy-only capture, so an
    // explicit-false or explicit-null value of a RENDERED field is not represented (a known, unchanged limitation); every field the wizard does not render survives
    // via baseProfileFields below.
    "      const flags = {};",
    "      const fieldValues = {};",
    "      for(const wf of window.__wizardFields) {",
    "        if(wf.type === 'boolean') { if(p[wf.id]) flags[wf.id] = true; }",
    "        else if(p[wf.id]) { fieldValues[wf.id] = p[wf.id]; }",
    "      }",
    // Each domain row keeps its full raw config so unrendered domain-level fields (videoTimeout, loginUrl, maxContinuousPlayback, dismissSelector) ride through a
    // resave; service and serviceTag drive the rendered inputs.
    "      const domains = (match.domains && match.domains.length > 0) ?",
    "        match.domains.map((d) => ({ config: d.config || {}, domain: d.domain, service: d.service || '', serviceTag: d.serviceTag || '' })) :",
    "        [{ config: {}, domain: '', service: '', serviceTag: '' }];",
    // Keep the full fetched profile as baseProfileFields. saveProfile starts from a copy of it and deletes only the rendered vocabulary, so unrendered profile-level
    // fields (channelSelector, clickSelector, fullscreenKey, fullscreenSelector, staticCapture) survive an edit-resave unchanged.
    "      profileWizard.state = {",
    "        baseProfile: p.extends || '', baseProfileFields: p, description: p.description || '',",
    "        domains: domains, editKey: key, editMode: true, fieldValues: fieldValues, flags: flags,",
    "        profileName: key, strategy: strat, strategyFields: strategyFields",
    "      };",
    "      profileWizard.open({ highestStep: 5, title: 'Edit Service Profile' });",
    "    } catch(e) { console.error('Profile data failed to load.', e); showToast('Failed to load profile data.', 'error'); }",
    "  };",

    // Pending import data stored while the import preview modal is open.
    "  let pendingImportData = null;",

    // Import a service pack via file picker - shows a preview modal before importing.
    "  window.startServiceImport = () => {",
    "    const input = document.createElement('input');",
    "    input.type = 'file';",
    "    input.accept = '.json,application/json';",
    "    input.onchange = () => {",
    "      if(!input.files || !input.files[0]) return;",
    "      const reader = new FileReader();",
    "      reader.onload = () => {",
    "        try {",
    "          const data = JSON.parse(reader.result);",
    "          pendingImportData = data;",
    "          const profileCount = data.profiles ? Object.keys(data.profiles).length : 0;",
    "          const domainCount = data.domains ? Object.keys(data.domains).length : 0;",
    "          const channelCount = data.channels ? Object.keys(data.channels).length : 0;",
    "          let html = '<table class=\"import-summary-table\">';",
    "          html += '<tr><td class=\"import-summary-label\">Pack name</td>';",
    "          html += '<td>' + escapeHtml(data.name || 'Unnamed') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Profiles</td>';",
    "          html += '<td>' + plural(profileCount, 'profile') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Domains</td>';",
    "          html += '<td>' + plural(domainCount, 'domain') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Channels</td>';",
    "          html += '<td>' + plural(channelCount, 'channel') + '</td></tr>';",
    "          html += '</table>';",
    "          if(channelCount > 0) {",
    "            html += '<div class=\"export-divider\"></div>';",
    "            html += '<label class=\"export-option-label\">';",
    "            html += '<input type=\"checkbox\" id=\"import-include-channels\" checked> Include ' + plural(channelCount, 'channel') + '</label>';",
    "            html += '<div class=\"export-hint\">Import the channel definitions from this pack. Uncheck to import only the service profiles and domains.</div>';",
    "          }",
    "          document.getElementById('import-modal-body').innerHTML = html;",
    "          document.getElementById('import-modal').style.display = 'flex';",
    "        } catch(e) {",
    "          console.error('Service pack JSON failed to parse.', e);",
    "          showToast('Invalid JSON file.', 'error');",
    "        }",
    "      };",
    "      reader.readAsText(input.files[0]);",
    "    };",
    "    input.click();",
    "  };",

    // Close the import preview modal.
    "  window.closeImportModal = () => {",
    "    document.getElementById('import-modal').style.display = 'none';",
    "    pendingImportData = null;",
    "  };",

    // Execute the import after the user confirms in the preview modal.
    "  window.executeImport = async () => {",
    "    if(!pendingImportData) return;",
    "    let skipChannels = false;",
    "    const cb = document.getElementById('import-include-channels');",
    "    if(cb && !cb.checked) skipChannels = true;",
    "    const body = { ...pendingImportData };",
    "    if(skipChannels) body.skipChannels = true;",
    "    try {",
    "      const res = await fetch('/config/profiles/import', {",
    "        body: JSON.stringify(body),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      closeImportModal();",
    "      if(result.success) {",
    "        let msg = 'Imported ' + plural(result.summary.profilesAdded, 'profile') + ', ' +",
    "          plural(result.summary.domainsAdded, 'domain') + ', ' + plural(result.summary.channelsAdded, 'channel') + '.';",
    "        if(result.warnings && result.warnings.length > 0) msg += ' Warnings: ' + result.warnings.join('; ');",
    "        showToast(msg, 'success');",
    "        if(result.panelHtml) { applyProfilePanel(result.panelHtml); }",
    "      } else {",
    "        showToast('Import failed: ' + extractErrorMessage(result, 'Unknown error.'), 'error');",
    "      }",
    "    } catch(err) { console.error('Service pack import request failed.', err); closeImportModal(); showToast('Import request failed.', 'error'); }",
    "  };",

    // Export a service pack. Opens a modal with profile checklist and options. Shows service name prominently for each profile with domain and channel counts.
    // The select-all row is hidden when there is only one profile since the single checkbox makes it redundant.
    "  window.startServiceExport = async () => {",
    "    try {",
    "      const res = await fetch('/config/profiles');",
    "      const data = await res.json();",
    "      const profiles = data.profiles || [];",
    "      if(profiles.length === 0) { showToast('No user profiles to export.', 'error'); return; }",
    "      const listDiv = document.getElementById('export-profile-list');",
    "      let html = '';",
    "      for(const p of profiles) {",
    "        const domainCount = p.domains ? p.domains.length : 0;",
    "        const channelCount = p.channelCount || 0;",
    "        let serviceName = '';",
    "        for(const dom of (p.domains || [])) {",
    "          if(dom.service) { serviceName = dom.service; break; }",
    "        }",
    "        const meta = [];",
    "        if(serviceName) meta.push(escapeHtml(serviceName));",
    "        meta.push(plural(domainCount, 'domain'));",
    "        meta.push(plural(channelCount, 'channel'));",
    "        html += '<label class=\"export-profile-item\">';",
    "        html += '<input type=\"checkbox\" class=\"export-profile-cb\" value=\"' + escapeHtml(p.key) + '\" checked>';",
    "        html += '<div class=\"export-profile-info\">';",
    "        html += '<div class=\"export-profile-name\">' + escapeHtml(p.key) + '</div>';",
    "        html += '<div class=\"export-profile-meta\">' + meta.join(' &middot; ') + '</div>';",
    "        html += '</div></label>';",
    "      }",
    "      listDiv.innerHTML = html;",
    "      document.getElementById('export-select-all').checked = true;",
    "      document.getElementById('export-select-all-row').style.display = (profiles.length > 1) ? '' : 'none';",
    "      document.getElementById('export-include-channels').checked = false;",
    "      document.getElementById('export-modal').style.display = 'flex';",
    "    } catch(e) { console.error('Profiles failed to load for export.', e); showToast('Failed to load profiles.', 'error'); }",
    "  };",

    // Toggle all export profile checkboxes.
    "  window.toggleExportAll = (master) => {",
    "    const cbs = document.querySelectorAll('.export-profile-cb');",
    "    for(const cb of cbs) cb.checked = master.checked;",
    "  };",

    // Close the export modal.
    "  window.closeExportModal = () => {",
    "    document.getElementById('export-modal').style.display = 'none';",
    "  };",

    // Execute the export by building the download URL from the selected profiles.
    "  window.executeExport = () => {",
    "    const cbs = document.querySelectorAll('.export-profile-cb:checked');",
    "    if(cbs.length === 0) { showToast('Select at least one profile.', 'error'); return; }",
    "    const keys = [];",
    "    for(const cb of cbs) keys.push(cb.value);",
    "    let url = '/config/profiles/export?profile=' + encodeURIComponent(keys.join(',')) + '&domains=1';",
    "    if(document.getElementById('export-include-channels').checked) url += '&channels=1';",
    "    closeExportModal();",
    "    window.location.href = url;",
    "  };",

    // Auto-generate a service tag from a service name: lowercase, strip non-alphanumeric.
    "  function autoServiceTag(name) {",
    "    return name.toLowerCase().replace(/[^a-z0-9]/g, '');",
    "  }",

    // The escapeHtml used throughout this script is the shared client-escape SSOT installed on window by the shared utilities script, which the page emits before
    // this one; there is no local copy here.

    // Pluralization helper for UI text: returns "1 domain", "2 domains", etc.
    "  function plural(n, word) {",
    "    return n + ' ' + word + (n === 1 ? '' : 's');",
    "  }",

    // Profile builder wizard. Uses the shared wizard controller for step navigation, indicator updates, and error display. The state object holds wizard-specific
    // form data (profile name, base profile, strategy, flags, domains, description).
    "  const profileWizard = createWizardController({",
    "    contentId: 'wizard-content',",
    "    errorId: 'wizard-error',",
    "    modalId: 'wizard-modal',",
    "    onRender: renderProfileStep,",
    "    onValidate: validateProfileStep,",
    "    stepCount: 5,",
    "    titleId: 'wizard-title'",
    "  });",

    // Render the current profile wizard step into the content area. Manages button visibility and delegates to the step-specific content renderer.
    "  function renderProfileStep(step) {",
    "    const content = document.getElementById('wizard-content');",
    "    if(!content) return;",

    // Show/hide navigation buttons based on the current step.
    "    if(step > 1) { profileWizard.show('wizard-back'); } else { profileWizard.hide('wizard-back'); }",
    "    if(step < 5) { profileWizard.show('wizard-next'); } else { profileWizard.hide('wizard-next'); }",
    "    if(step === 5) { profileWizard.show('wizard-save'); profileWizard.show('wizard-save-test'); }",
    "    else { profileWizard.hide('wizard-save'); profileWizard.hide('wizard-save-test'); }",

    "    let html = '';",
    "    const s = profileWizard.state;",

    // Step 1: Base Profile.
    "    if(step === 1) {",
    "      html += '<div class=\"field-group\">';",
    "      html += '<label class=\"wizard-label\" for=\"wizard-profile-name\">Profile Name</label>';",
    "      const nameReadonly = s.editMode ? ' readonly style=\"opacity: 0.6; cursor: not-allowed;\"' : '';",
    "      html += '<input type=\"text\" id=\"wizard-profile-name\" value=\"' + escapeHtml(s.profileName) + '\" placeholder=\"e.g., myService\"' + nameReadonly + '>';",
    "      html += '<div class=\"field-hint\">' + (s.editMode ? 'Profile name cannot be changed.' :",
    "        'Unique identifier. Letters, numbers, and hyphens only.') + '</div>';",
    "      html += '</div>';",
    "      html += '<label class=\"wizard-label\">Base Profile</label>';",
    "      const profiles = window.__wizardProfiles || {};",
    "      const cats = [",
    "        { key: 'api', title: 'Fullscreen API',",
    "          desc: 'For single-channel sites that require JavaScript\\'s requestFullscreen() API instead of keyboard shortcuts.' },",
    "        { key: 'keyboard', title: 'Keyboard Fullscreen',",
    "          desc: 'For single-channel sites that use the \\'f\\' key to toggle fullscreen mode.' },",
    "        { key: 'multiChannel', title: 'Multi-Channel',",
    "          desc: 'For sites that host multiple live channels on a single page.' },",
    "        { key: 'special', title: 'Special',",
    "          desc: 'For non-standard use cases like static pages without video.' },",
    "        { key: 'custom', title: 'Custom', desc: '' }",
    "      ];",
    "      for(const cat of cats) {",
    "        const items = (profiles[cat.key] || []).filter((p) => !s.editMode || p.name !== s.editKey);",
    "        if(items.length === 0) continue;",
    "        html += '<div class=\"wizard-profile-category\">';",
    "        html += '<h4>' + cat.title + '</h4>';",
    "        if(cat.desc) html += '<div class=\"wizard-category-desc\">' + escapeHtml(cat.desc) + '</div>';",
    "        for(const p of items) {",
    "          const checked = (s.baseProfile === p.name) ? ' checked' : '';",
    "          html += '<label class=\"wizard-profile-option\">';",
    "          html += '<input type=\"radio\" name=\"baseProfile\" value=\"' + p.name + '\"' + checked + '>';",
    "          const sumTag = p.summary ? ' <span class=\"profile-option-summary\">(' + escapeHtml(p.summary) + ')</span>' : '';",
    "          html += '<div><div class=\"profile-option-name\">' + escapeHtml(p.name) + sumTag + '</div>';",
    "          html += '<div class=\"profile-option-desc\">' + escapeHtml(p.description) + '</div></div>';",
    "          html += '</label>';",
    "        }",
    "        html += '</div>';",
    "      }",
    "    }",

    // Step 2: Channel Selection Strategy. Strategies and their fields are rendered from the server-side registry (window.__wizardStrategies).
    "    if(step === 2) {",
    "      html += '<label class=\"wizard-label\">Channel Selection Strategy</label>';",
    "      const strategies = window.__wizardStrategies;",
    "      for(const st of strategies) {",
    "        const checked = (s.strategy === st.id) ? ' checked' : '';",
    "        html += '<label class=\"wizard-strategy-option\">';",
    "        html += '<input type=\"radio\" name=\"strategy\" value=\"' + st.id + '\"' + checked + '>';",
    "        html += '<div><div class=\"wizard-strategy-label\">' + st.name + '</div>';",
    "        html += '<div class=\"wizard-strategy-desc\">' + st.description + '</div></div>';",
    "        html += '</label>';",
    "      }",
    "      const currentStrat = strategies.find((st) => st.id === s.strategy);",
    "      if(currentStrat && currentStrat.fields.length > 0) {",
    "        html += '<hr style=\"border: none; border-top: 1px solid var(--border-default); margin: 16px 0;\">';",
    "        for(const f of currentStrat.fields) {",
    "          if(f.type === 'text') {",
    "            const val = escapeHtml(s.strategyFields[f.id] || '');",
    "            const optLabel = f.required ? '' : ' <span style=\"color: var(--text-muted);\">(optional)</span>';",
    "            html += '<div class=\"field-group\">';",
    "            html += '<label class=\"wizard-label\" for=\"wizard-sf-' + f.id + '\">' + f.label + optLabel + '</label>';",
    "            html += '<input type=\"text\" id=\"wizard-sf-' + f.id + '\" data-field=\"' + f.id + '\" value=\"' + val + '\"';",
    "            if(f.placeholder) html += ' placeholder=\"' + escapeHtml(f.placeholder) + '\"';",
    "            html += '>';",
    "            if(f.hint) html += '<div class=\"field-hint\">' + f.hint + '</div>';",
    "            html += '</div>';",
    "          } else if(f.type === 'boolean') {",
    "            const boolChecked = s.strategyFields[f.id] ? ' checked' : '';",
    "            html += '<label class=\"wizard-flag\">';",
    "            html += '<input type=\"checkbox\" data-field=\"' + f.id + '\"' + boolChecked + '>';",
    "            html += '<div><div class=\"wizard-flag-label\">' + f.label + '</div>';",
    "            if(f.hint) html += '<div class=\"wizard-flag-desc\">' + f.hint + '</div>';",
    "            html += '</div></label>';",
    "          }",
    "        }",
    "      }",
    "    }",

    // Step 3: Profile Fields. Both the boolean flags and the text selectors are rendered from the server-side registry (window.__wizardFields), branching on type:
    // booleans are checkboxes described by their description, text fields are inputs described by their hint.
    "    if(step === 3) {",
    "      html += '<label class=\"wizard-label\">Profile Flags</label>';",
    "      html += '<div class=\"field-hint\" style=\"margin-bottom: 12px;\">These override the base profile. ' +",
    "        'Only change what differs from ' + s.baseProfile + '.</div>';",
    "      const wizFields = window.__wizardFields;",
    "      for(const f of wizFields) {",
    "        if(f.type !== 'boolean') continue;",
    "        const checked = s.flags[f.id] ? ' checked' : '';",
    "        html += '<label class=\"wizard-flag\">';",
    "        html += '<input type=\"checkbox\" name=\"flag-' + f.id + '\"' + checked + '>';",
    "        html += '<div><div class=\"wizard-flag-label\">' + f.label + '</div>';",
    "        html += '<div class=\"wizard-flag-desc\">' + f.description + '</div></div>';",
    "        html += '</label>';",
    "      }",
    "      for(const f of wizFields) {",
    "        if(f.type !== 'text') continue;",
    "        const fieldVal = escapeHtml(s.fieldValues[f.id] || '');",
    "        html += '<div class=\"field-group\" style=\"margin-top: 12px;\">';",
    "        html += '<label class=\"wizard-label\" for=\"wizard-field-' + f.id + '\">' + f.label +",
    "          ' <span style=\"color: var(--text-muted);\">(optional)</span></label>';",
    "        html += '<input type=\"text\" class=\"wizard-field-input\" data-field-id=\"' + f.id + '\" id=\"wizard-field-' + f.id + '\" value=\"' + fieldVal +",
    "          '\" placeholder=\"' + escapeHtml(f.placeholder || '') + '\">';",
    "        html += '<div class=\"field-hint\">' + (f.hint || '') + '</div>';",
    "        html += '</div>';",
    "      }",
    "    }",

    // Step 4: Domain Mapping.
    "    if(step === 4) {",
    "      html += '<label class=\"wizard-label\">Domain Mapping</label>';",
    "      html += '<div class=\"field-hint\" style=\"margin-bottom: 12px;\">Map a streaming site domain to this profile.</div>';",
    "      for(const [ di, d ] of s.domains.entries()) {",
    "        html += '<div class=\"wizard-domain-row\" data-domain-idx=\"' + di + '\">';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label class=\"wizard-label\">Domain</label>';",
    "        html += '<input type=\"text\" class=\"domain-input\" value=\"' + escapeHtml(d.domain) + '\" placeholder=\"e.g., watch.sling.com\">';",
    "        html += '</div>';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label class=\"wizard-label\">Service Name</label>';",
    "        html += '<input type=\"text\" class=\"provider-input\" value=\"' + escapeHtml(d.service) + '\" placeholder=\"e.g., Sling TV\">';",
    "        html += '</div>';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label class=\"wizard-label\">Service Tag <span style=\"color: var(--text-muted);\">(auto-filled)</span></label>';",
    "        html += '<input type=\"text\" class=\"provider-tag-input\" value=\"' + escapeHtml(d.serviceTag) + '\" placeholder=\"auto-generated\">';",
    "        html += '<div class=\"field-hint\">Identifier for the service filter. Auto-generated from service name.</div>';",
    "        html += '</div>';",
    "        html += '</div>';",
    "      }",
    "      html += '<button type=\"button\" class=\"wizard-add-domain\" id=\"wizard-add-domain-btn\">+ Add another domain</button>';",
    "    }",

    // Step 5: Review and Save.
    "    if(step === 5) {",
    "      html += '<label class=\"wizard-label\">Review</label>';",
    "      html += '<table class=\"wizard-review-table\">';",
    "      html += '<tr><td>Profile</td><td>' + escapeHtml(s.profileName) + '</td></tr>';",
    "      html += '<tr><td>Extends</td><td>' + escapeHtml(s.baseProfile) + '</td></tr>';",
    "      html += '<tr><td>Strategy</td><td>' + escapeHtml(s.strategy) + '</td></tr>';",
    "      const domainList = s.domains.filter((d) => d.domain).map((d) => escapeHtml(d.domain)).join(', ');",
    "      html += '<tr><td>Domain(s)</td><td>' + (domainList || 'none') + '</td></tr>';",
    "      const serviceList = s.domains.filter((d) => d.service).map((d) => escapeHtml(d.service)).join(', ');",
    "      html += '<tr><td>Service</td><td>' + (serviceList || 'none') + '</td></tr>';",
    "      if(s.strategy !== 'none') {",
    "        const reviewStrat = window.__wizardStrategies.find((st) => st.id === s.strategy);",
    "        if(reviewStrat) {",
    "          for(const rf of reviewStrat.fields) {",
    "            const rv = s.strategyFields[rf.id];",
    "            if(rf.type === 'text' && rv) {",
    "              html += '<tr><td>' + escapeHtml(rf.label.replace(/ \\(CSS\\)/, '')) + '</td><td><code>' + escapeHtml(rv) + '</code></td></tr>';",
    "            } else if(rf.type === 'boolean' && rv) {",
    "              html += '<tr><td>' + escapeHtml(rf.label) + '</td><td>Yes</td></tr>';",
    "            }",
    "          }",
    "        }",
    "      }",
    "      const flagNames = Object.keys(s.flags).filter((k) => s.flags[k]);",
    "      if(flagNames.length > 0) {",
    "        html += '<tr><td>Flags</td><td>' + escapeHtml(flagNames.join(', ')) + '</td></tr>';",
    "      }",
    "      for(const rtf of window.__wizardFields) {",
    "        if(rtf.type !== 'text') continue;",
    "        const rtv = s.fieldValues[rtf.id];",
    "        if(rtv) html += '<tr><td>' + escapeHtml(rtf.label.replace(/ \\(CSS\\)/, '')) + '</td><td><code>' + escapeHtml(rtv) + '</code></td></tr>';",
    "      }",
    "      html += '</table>';",
    "      html += '<div class=\"field-group\" style=\"margin-top: 16px;\">';",
    "      html += '<label class=\"wizard-label\" for=\"wizard-description\">Description <span style=\"color: var(--text-muted);\">(optional)</span></label>';",
    "      html += '<textarea id=\"wizard-description\" placeholder=\"Optional description for documentation.\">' + escapeHtml(s.description) + '</textarea>';",
    "      html += '</div>';",
    "    }",

    "    content.innerHTML = html;",

    // Attach live event handlers after rendering.
    "    attachProfileHandlers();",
    "  }",

    // Attach event handlers to dynamically rendered profile wizard inputs.
    "  function attachProfileHandlers() {",
    "    const s = profileWizard.state;",

    // Step 1: profile name and base profile radio.
    "    const nameInput = document.getElementById('wizard-profile-name');",
    "    if(nameInput) nameInput.addEventListener('input', function() { s.profileName = this.value; });",
    "    const radios = document.querySelectorAll('input[name=\"baseProfile\"]');",
    "    for(const radio of radios) {",
    "      radio.addEventListener('change', function() { s.baseProfile = this.value; });",
    "    }",

    // Step 2: strategy radio and strategy field inputs. Text and boolean fields are bound by data-field attribute. Strategy radio triggers a re-render to show
    // the selected strategy's fields.
    "    const stratRadios = document.querySelectorAll('input[name=\"strategy\"]');",
    "    for(const stratRadio of stratRadios) {",
    "      stratRadio.addEventListener('change', function() { s.strategy = this.value; renderProfileStep(profileWizard.getStep()); });",
    "    }",
    "    const sfTextInputs = document.querySelectorAll('#wizard-content input[type=\"text\"][data-field]');",
    "    for(const sfTextInput of sfTextInputs) {",
    "      sfTextInput.addEventListener('input', function() { s.strategyFields[this.getAttribute('data-field')] = this.value; });",
    "    }",
    "    const sfCheckInputs = document.querySelectorAll('#wizard-content input[type=\"checkbox\"][data-field]');",
    "    for(const sfCheckInput of sfCheckInputs) {",
    "      sfCheckInput.addEventListener('change', function() {",
    "        if(this.checked) { s.strategyFields[this.getAttribute('data-field')] = true; }",
    "        else { delete s.strategyFields[this.getAttribute('data-field')]; }",
    "      });",
    "    }",

    // Step 3: flag checkboxes and text selector inputs. Text fields bind by their data-field-id into fieldValues.
    "    const flagCbs = document.querySelectorAll('input[name^=\"flag-\"]');",
    "    for(const flagCb of flagCbs) {",
    "      flagCb.addEventListener('change', function() {",
    "        const flagName = this.name.replace('flag-', '');",
    "        if(this.checked) { s.flags[flagName] = true; } else { delete s.flags[flagName]; }",
    "      });",
    "    }",
    "    const fieldInputs = document.querySelectorAll('.wizard-field-input[data-field-id]');",
    "    for(const fieldInput of fieldInputs) {",
    "      fieldInput.addEventListener('input', function() { s.fieldValues[this.getAttribute('data-field-id')] = this.value; });",
    "    }",

    // Step 4: add-domain button and domain inputs with auto-fill for service tag. Per-iteration const bindings from for...of.entries() capture the correct index
    // in each closure - no IIFE wrapper needed.
    "    const addDomainBtn = document.getElementById('wizard-add-domain-btn');",
    "    if(addDomainBtn) addDomainBtn.addEventListener('click', addWizardDomain);",
    "    for(const [ idx, row ] of document.querySelectorAll('.wizard-domain-row').entries()) {",
    "      const domInput = row.querySelector('.domain-input');",
    "      const provInput = row.querySelector('.provider-input');",
    "      const tagInput = row.querySelector('.provider-tag-input');",
    "      if(domInput) domInput.addEventListener('input', function() { s.domains[idx].domain = this.value; });",
    "      if(provInput) provInput.addEventListener('input', function() {",
    "        s.domains[idx].service = this.value;",
    "        const tag = autoServiceTag(this.value);",
    "        s.domains[idx].serviceTag = tag;",
    "        if(tagInput) tagInput.value = tag;",
    "      });",
    "      if(tagInput) tagInput.addEventListener('input', function() { s.domains[idx].serviceTag = this.value; });",
    "    }",

    // Step 5: description textarea.
    "    const descInput = document.getElementById('wizard-description');",
    "    if(descInput) descInput.addEventListener('input', function() { s.description = this.value; });",
    "  }",

    // Validate the current profile wizard step. Returns an error message or empty string if valid.
    "  function validateProfileStep(step) {",
    "    const s = profileWizard.state;",
    "    if(step === 1) {",
    "      if(!s.editMode) {",
    "        if(!s.profileName.trim()) return 'Profile name is required.';",
    "        if(!/^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(s.profileName))",
    "          return 'Must start with a letter, contain only letters, numbers, and hyphens, and not end with a hyphen.';",
    "        if(s.profileName.length > 50) return 'Profile name must be 50 characters or less.';",
    "      }",
    "      if(!s.baseProfile) return 'Select a base profile.';",
    "    }",
    "    if(step === 2) {",
    "      const valStrat = window.__wizardStrategies.find((st) => st.id === s.strategy);",
    "      if(valStrat) {",
    "        for(const vf of valStrat.fields) {",
    "          if(vf.required && (vf.type === 'text') && !(s.strategyFields[vf.id] || '').trim()) {",
    "            return vf.label.replace(/ \\(CSS\\)/, '') + ' is required for the ' + valStrat.name + ' strategy.';",
    "          }",
    "        }",
    "      }",
    "    }",
    "    if(step === 4) {",
    "      const hasDomain = s.domains.some((d) => d.domain.trim());",
    "      if(!hasDomain) return 'At least one domain is required.';",
    "    }",
    "    return '';",
    "  }",

    // Open the profile builder wizard and reset state for a new profile.
    "  window.openWizard = () => {",
    "    profileWizard.state = {",
    "      baseProfile: '', baseProfileFields: {}, description: '',",
    "      domains: [{ config: {}, domain: '', service: '', serviceTag: '' }], editKey: null, editMode: false,",
    "      fieldValues: {}, flags: {}, profileName: '', strategy: 'none', strategyFields: {}",
    "    };",
    "    profileWizard.open({ title: 'New Service Profile' });",
    "  };",

    // Add another domain row to step 4 and re-render.
    "  function addWizardDomain() {",
    "    profileWizard.state.domains.push({ config: {}, domain: '', service: '', serviceTag: '' });",
    "    renderProfileStep(profileWizard.getStep());",
    "  }",

    // Save the profile to the server. Concurrent edits of the same profile resolve last-save-wins: the rebuild starts from the snapshot fetched when the wizard opened,
    // matching the server's whole-replace semantics. The profile is a copy of the full fetched profile (empty for a new one) with only the wizard's rendered vocabulary
    // deleted and
    // re-applied, so every field the wizard does not render round-trips unchanged while a cleared rendered field is a real deletion. The server's whole-replace
    // semantics are unchanged; a field outside the SiteProfile allowlist that rode through here surfaces as an explicit validation error, which is the honest outcome.
    "  window.saveProfile = async (andTest) => {",
    "    const s = profileWizard.state;",
    // The wizard's rendered vocabulary: every field id it renders plus the structural keys it owns. Deleting these from the base copy is what makes a cleared field a
    // deletion; everything else in the copy is preserved verbatim.
    "    const vocabulary = window.__wizardFields.map((f) => f.id).concat(['extends', 'description', 'channelSelection']);",
    "    const profile = Object.assign({}, s.baseProfileFields || {});",
    "    for(const vk of vocabulary) { delete profile[vk]; }",
    "    profile.extends = s.baseProfile;",
    // Rebuild channelSelection rather than dropping it: preserve the base's unrendered sub-fields (listSelector, scrollSelector, scrollTarget) by starting from a copy
    // and removing only the CHOSEN strategy's rendered field ids, so a strategy switch cannot leave stale rendered values behind. When the strategy is 'none' no
    // channelSelection key is written at all - the sub-fields configure a strategy the user just removed.
    "    if(s.strategy !== 'none') {",
    "      const saveStrat = window.__wizardStrategies.find((st) => st.id === s.strategy);",
    "      const cs = Object.assign({}, (s.baseProfileFields && s.baseProfileFields.channelSelection) || {});",
    "      if(saveStrat) { for(const rf of saveStrat.fields) { delete cs[rf.id]; } }",
    "      cs.strategy = s.strategy;",
    "      if(saveStrat) {",
    "        for(const sf of saveStrat.fields) {",
    "          const sfVal = s.strategyFields[sf.id];",
    "          if(sf.type === 'text' && sfVal) { cs[sf.id] = sfVal; }",
    "          else if(sf.type === 'boolean' && sfVal) { cs[sf.id] = true; }",
    "        }",
    "      }",
    "      profile.channelSelection = cs;",
    "    }",
    // Re-apply the rendered profile fields: boolean flags that are set, text selectors that are non-empty. A cleared text field or an unchecked flag simply is not
    // re-added, which - because the vocabulary was deleted above - deletes it from the round-tripped profile.
    "    for(const f of window.__wizardFields) {",
    "      if(f.type === 'boolean') { if(s.flags[f.id]) profile[f.id] = true; }",
    "      else { const tv = (s.fieldValues[f.id] || '').trim(); if(tv) profile[f.id] = tv; }",
    "    }",
    "    if(s.description) profile.description = s.description;",
    // Each domain entry preserves its full raw config (unrendered fields ride through), then re-applies the profile key and the rendered service/serviceTag - deleting
    // them when the inputs are cleared. A row whose domain string was edited carries its config to the new domain key (rename semantics).
    "    const domains = {};",
    "    for(const d of s.domains) {",
    "      if(d.domain.trim()) {",
    "        const entry = Object.assign({}, d.config || {});",
    "        entry.profile = s.profileName;",
    "        if(d.service.trim()) entry.service = d.service.trim(); else delete entry.service;",
    "        if(d.serviceTag.trim()) entry.serviceTag = d.serviceTag.trim(); else delete entry.serviceTag;",
    "        domains[d.domain.trim()] = entry;",
    "      }",
    "    }",
    "    const body = { domains: domains, key: s.profileName, profile: profile };",
    "    try {",
    "      const res = await fetch('/config/profiles', {",
    "        body: JSON.stringify(body),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(data.success) {",
    "        profileWizard.close();",
    "        if(data.panelHtml) { applyProfilePanel(data.panelHtml); }",
    "        if(andTest && s.domains[0] && s.domains[0].domain) {",
    "          startProfileTest(s.domains[0].domain);",
    "        }",
    "      } else {",
    "        profileWizard.setError(extractErrorMessage(data, 'Failed to save profile.'));",
    "      }",
    "    } catch(err) {",
    "      console.error('Profile save request failed.', err);",
    "      profileWizard.setError('Request failed.');",
    "    }",
    "  };",

    // Test flow: open a browser to a URL with the profile applied and allow selector checking.
    "  let testSelectors = {};",

    // Start a profile test by opening the browser to a URL.
    "  window.startProfileTest = async (url) => {",
    "    const s = profileWizard.state;",
    "    testSelectors = {};",
    "    if(s.strategy !== 'none' && s.strategyFields.matchSelector) testSelectors.matchSelector = s.strategyFields.matchSelector;",
    "    if(s.strategyFields.playSelector) testSelectors.playSelector = s.strategyFields.playSelector;",
    "    if(s.fieldValues.hideSelector) testSelectors.hideSelector = s.fieldValues.hideSelector;",
    "    if(s.fieldValues.dismissSelector) testSelectors.dismissSelector = s.fieldValues.dismissSelector;",
    "    const testUrl = url.includes('://') ? url : 'https://' + url;",
    "    try {",
    "      const res = await fetch('/config/profiles/test', {",
    "        body: JSON.stringify({ url: testUrl }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(data.success) {",
    "        document.getElementById('test-modal').style.display = 'flex';",
    "        document.getElementById('test-selector-results').style.display = 'none';",
    "        document.getElementById('test-check-btn').style.display = ",
    "          Object.keys(testSelectors).length > 0 ? '' : 'none';",
    "      } else {",
    "        showToast('Failed to start test: ' + extractErrorMessage(data, 'Unknown error.'), 'error');",
    "      }",
    "    } catch(e) { console.error('Profile test failed to start.', e); showToast('Failed to start test.', 'error'); }",
    "  };",

    // Check CSS selectors against the live page.
    "  window.checkSelectors = async () => {",
    "    if(Object.keys(testSelectors).length === 0) return;",
    "    try {",
    "      const res = await fetch('/config/profiles/test/check', {",
    "        body: JSON.stringify({ selectors: testSelectors }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      const resultsDiv = document.getElementById('test-selector-results');",
    "      if(!data.success || !data.results) {",
    "        resultsDiv.innerHTML = '<p style=\"color: var(--status-error-text);\">Check failed.</p>';",
    "        resultsDiv.style.display = 'block';",
    "        return;",
    "      }",
    "      let html = '<table style=\"width: 100%; font-size: 13px; margin: 12px 0;\">';",
    "      const names = Object.keys(data.results);",
    "      for(const name of names) {",
    "        const r = data.results[name];",
    "        const color = r.valid && r.count > 0 ? 'var(--status-success-text)' : 'var(--status-error-text)';",
    "        const text = !r.valid ? 'Invalid selector' : r.count + ' element(s)';",
    "        html += '<tr><td style=\"padding: 4px 8px;\">' + escapeHtml(name) + '</td>';",
    "        html += '<td style=\"padding: 4px 8px; color: ' + color + ';\">' + text + '</td></tr>';",
    "      }",
    "      html += '</table>';",
    "      resultsDiv.innerHTML = html;",
    "      resultsDiv.style.display = 'block';",
    "    } catch(e) {",
    "      const resultsDiv = document.getElementById('test-selector-results');",
    "      resultsDiv.innerHTML = '<p style=\"color: var(--status-error-text);\">Check request failed.</p>';",
    "      resultsDiv.style.display = 'block';",
    "    }",
    "  };",

    // End the test flow and close the test dialog.
    "  window.endProfileTest = async () => {",
    "    try {",
    "      const res = await fetch('/config/profiles/test/done', { method: 'POST' });",
    "      const data = await res.json();",
    "      document.getElementById('test-modal').style.display = 'none';",
    "      if(data.panelHtml) { applyProfilePanel(data.panelHtml); }",
    "    } catch(err) {",
    "      console.error('Profile test end request failed.', err);",
    "      document.getElementById('test-modal').style.display = 'none';",
    "    }",
    "  };",

    // Read embedded JSON data for the browse modal. Service list and guide URLs are embedded server-side. Channel state (lineup matching) is provided by
    // the annotated discovery response, not by embedded data.
    "  let browseServices = [];",
    "  let browseGuideUrls = {};",
    "  try {",
    "    const pEl = document.getElementById('browse-services-data');",
    "    if(pEl) browseServices = JSON.parse(pEl.textContent || '[]');",
    "    const gEl = document.getElementById('browse-guide-urls-data');",
    "    if(gEl) browseGuideUrls = JSON.parse(gEl.textContent || '{}');",
    "  } catch(e) { console.warn('Embedded browse services data failed to parse.', e); }",

    // Browse Channels wizard. Steps: Service (picker grid) and Channels (discovery + channel list). Uses the shared wizard controller for step navigation
    // and indicator updates. The state object tracks the selected service slug and label, and the filtered service list for the current session.
    "  const browseWizard = createWizardController({",
    "    contentId: 'browse-content',",
    "    modalId: 'browse-modal',",
    "    onRender: renderBrowseStep,",
    "    onValidate: (step) => (step === 1 && !browseWizard.state.slug) ? 'Select a service.' : '',",
    "    stepCount: 2,",
    "    titleId: 'browse-title'",
    "  });",

    // Open the browse modal. If only one service is available (or in the filter), skip step 1 and open directly on step 2 with the service pre-selected.
    "  window.openBrowseModal = () => {",

    // Determine which services to show. Filter to services that are enabled in the service filter if a filter is active.
    "    const enabledFilter = [];",
    "    const chips = document.querySelectorAll('.provider-chip');",
    "    for(const chip of chips) {",
    "      const tag = chip.getAttribute('data-tag');",
    "      if(tag) enabledFilter.push(tag);",
    "    }",
    "    let available = browseServices;",
    "    if(enabledFilter.length > 0) {",
    "      available = browseServices.filter((p) => enabledFilter.includes(p.slug));",
    "    }",

    // If no discoverable services match the filter, show all services.
    "    if(available.length === 0) available = browseServices;",

    // If exactly one service is available, skip the picker and go straight to channel discovery on step 2.
    "    if(available.length === 1) {",
    "      browseWizard.state = { available: available, label: available[0].label, slug: available[0].slug };",
    "      browseWizard.open({ highestStep: 2, step: 2 });",
    "      return;",
    "    }",

    "    browseWizard.state = { available: available, label: null, slug: null };",
    "    browseWizard.open();",
    "  };",

    // Select a service from the picker grid and advance to step 2.
    "  function selectBrowseService(slug, label) {",
    "    browseWizard.state.slug = slug;",
    "    browseWizard.state.label = label;",
    "    browseWizard.next();",
    "  }",

    // Render the current browse step. Step 1: service picker grid. Step 2: channel discovery and list.
    "  function renderBrowseStep(step) {",
    "    const content = document.getElementById('browse-content');",

    // Show/hide navigation buttons. Back is only available on step 2 when there are multiple services.
    "    if(step > 1 && browseWizard.state.available.length > 1) { browseWizard.show('browse-back'); }",
    "    else { browseWizard.hide('browse-back'); }",

    // Reset title and apply button on each render.
    "    browseWizard.setTitle('Browse Channels');",
    "    browseWizard.hide('browse-add-btn');",

    // Step 1: Service picker grid. Clear the service selection so the user must pick again (prevents the step indicator from jumping to step 2 with a stale
    // service after navigating back).
    "    if(step === 1) {",
    "      browseWizard.state.slug = null;",
    "      browseWizard.state.label = null;",
    "      const available = browseWizard.state.available;",
    "      let html = '<p class=\"wizard-hint\">Select a service to see its available channels.</p>';",
    "      html += '<div class=\"wizard-provider-grid\">';",
    "      for(const p of available) {",
    "        html += '<div class=\"wizard-provider-card\" data-slug=\"' + escapeHtml(p.slug) + '\" data-label=\"' + escapeHtml(p.label) + '\">';",
    // serviceIconHtml escapes its name argument internally through the shared escapeHtml SSOT, so the label is passed raw here; escaping it again would double-encode.
    "        html += serviceIconHtml(p.domain, p.label, 'provider-icon', 'provider-icon-text', 'both', p.iconUrl || '');",
    "        html += '</div>';",
    "      }",
    "      html += '</div>';",
    "      content.innerHTML = html;",

    // Attach click handlers to service cards programmatically. The handler reads slug and label from data attributes, avoiding inline onclick and global scope.
    "      const cards = content.querySelectorAll('.wizard-provider-card');",
    "      for(const card of cards) {",
    "        card.addEventListener('click', function() {",
    "          selectBrowseService(this.getAttribute('data-slug'), this.getAttribute('data-label'));",
    "        });",
    "      }",
    "      return;",
    "    }",

    // Step 2: Fetch discovered channels and render the channel list.
    "    const slug = browseWizard.state.slug;",
    "    const label = browseWizard.state.label;",

    // Show a spinner while fetching channels.
    "    content.innerHTML = '<div class=\"wizard-spinner\">Discovering channels from ' + escapeHtml(label) + '...</div>';",

    // Fetch discovered channels from the service endpoint.
    "    (async () => {",
    "      try {",
    "        const r = await fetch('/services/' + encodeURIComponent(slug) + '/channels?lineup=true');",
    "        if(!r.ok) { const d = await r.json(); throw new Error(extractErrorMessage(d, 'Discovery failed.')); }",
    "        const channels = await r.json();",
    "        if(browseWizard.state.slug !== slug) return;",
    "        renderBrowseChannelList(channels, slug, label);",
    "      } catch(err) {",
    "        if(browseWizard.state.slug !== slug) return;",
    "        content.innerHTML = '<div class=\"wizard-empty\"><div class=\"wizard-empty-title\">Could not discover channels.</div>' +",
    "          escapeHtml(err.message || 'Check that the browser is running and you are signed in to ' + label + '.') + '</div>';",
    "      }",
    "    })();",
    "  }",

    // Render the channel list with three-state checkboxes. Each discovered channel carries an optional lineup field from the server's annotation layer.
    // When lineup is present but the entry is disabled, the channel is "disabled" regardless of currentTag. Otherwise, when lineup.currentTag matches the
    // browsed service slug, the channel is "current" (checked); when it differs, the channel is "switch" (indeterminate). When lineup is absent, the
    // channel is "new" (empty).
    "  function renderBrowseChannelList(channels, slug, label) {",
    "    if(!channels || channels.length === 0) {",
    "      document.getElementById('browse-content').innerHTML =",
    "        '<div class=\"wizard-empty\"><div class=\"wizard-empty-title\">No channels found.</div>' +",
    "        'Make sure you are signed in to ' + escapeHtml(label) + ' in the browser.</div>';",
    "      return;",
    "    }",

    // Build the channel list HTML with hint, legend, search filter, and three-state checkboxes.
    "    let html = '';",
    "    html += '<p class=\"wizard-hint\">Check to add or switch to this service. Uncheck to remove. Changes take effect when you click Apply.</p>';",
    "    html += '<div class=\"browse-toolbar\">';",
    "    html += '<label class=\"browse-select-all\">';",
    "    html += '<input type=\"checkbox\" id=\"browse-select-all-cb\">';",
    "    html += 'Select All</label>';",
    "    html += '<input type=\"text\" class=\"browse-search\" id=\"browse-search\" placeholder=\"Filter channels...\">';",
    "    html += '</div>';",
    "    html += '<div class=\"browse-legend\">';",
    "    html += '<span class=\"browse-legend-item\"><input type=\"checkbox\" disabled> New channel</span>';",
    "    html += '<span class=\"browse-legend-item\"><input type=\"checkbox\" class=\"browse-legend-indeterminate\" disabled> Available via another service</span>';",
    "    html += '<span class=\"browse-legend-item\"><input type=\"checkbox\" checked disabled> Active on this service</span>';",
    "    html += '</div>';",
    "    html += '<div class=\"browse-channel-list\" id=\"browse-channel-list\">';",

    // Render each discovered channel. The lineup field from the server annotation determines the checkbox state.
    "    for(const ch of channels) {",
    "      const lu = ch.lineup;",

    // Determine the channel's state from the server-provided lineup annotation: new (no lineup data), disabled (predefined but disabled),
    // switch (exists via a different service), or current (already using this service).
    "      let state = 'new';",
    "      let stateLabel = '';",
    "      if(lu) {",
    "        if(!lu.enabled) {",
    "          state = 'disabled';",
    "          stateLabel = 'Disabled';",
    "        } else if(lu.currentTag === slug) {",
    "          state = 'current';",
    "          stateLabel = lu.source === 'predefined' ? 'Predefined' : 'User channel';",
    "        } else {",
    "          state = 'switch';",
    "          stateLabel = 'via ' + lu.currentService;",
    "        }",
    "      }",

    "      const itemClass = 'browse-channel-item browse-state-' + state;",
    "      const searchName = ((lu && lu.displayName) ? lu.displayName : ch.name).toLowerCase();",
    "      html += '<label class=\"' + itemClass + '\" data-name=\"' + escapeHtml(searchName) + '\">';",

    // Checkbox with data attributes for state tracking and submission.
    "      html += '<input type=\"checkbox\" class=\"browse-channel-cb\"';",
    "      html += ' data-name=\"' + escapeHtml(ch.name) + '\"';",
    "      html += ' data-selector=\"' + escapeHtml(ch.channelSelector) + '\"';",
    "      html += ' data-original=\"' + state + '\"';",
    "      if(lu) html += ' data-canonical=\"' + escapeHtml(lu.canonicalKey) + '\" data-has-alternatives=\"' + (lu.hasAlternatives ? 'true' : 'false') + '\"';",
    "      if(ch.stationId) html += ' data-station-id=\"' + escapeHtml(ch.stationId) + '\"';",
    "      if(state === 'current') html += ' checked';",
    "      html += '>';",

    // Channel name with optional logo and affiliate. When the channel matches a lineup entry, use the predefined display name so the browse modal shows the
    // same names as the channels table. For new channels (no lineup match), use the raw discovery name.
    "      const channelName = (lu && lu.displayName) ? lu.displayName : ch.name;",
    "      html += '<span class=\"browse-channel-name\">';",
    // channelDisplayHtml escapes its name argument internally, so channelName is passed raw; escaping it here too would double-encode.
    "      html += channelDisplayHtml(lu ? lu.logoUrl || '' : '', channelName, 'browse-channel-logo', 'browse-channel-text', 'both');",
    "      if(ch.affiliate) html += ' <span class=\"browse-affiliate\">(' + escapeHtml(ch.affiliate) + ')</span>';",
    "      html += '</span>';",

    // Right side: state label and tier badge.
    "      html += '<span class=\"browse-channel-meta\">';",
    "      if(stateLabel) html += '<span class=\"browse-state-label\">' + escapeHtml(stateLabel) + '</span>';",
    "      if(ch.tier === 'free') html += '<span class=\"browse-tier-badge tier-free\">Free</span>';",
    "      html += '</span>';",

    "      html += '</label>';",
    "    }",

    "    html += '</div>';",
    "    document.getElementById('browse-content').innerHTML = html;",
    "    browseWizard.setTitle('Browse Channels <span class=\"browse-header-count\">(' + escapeHtml(label) + ' \\u2014 ' + channels.length + ' channels)</span>');",

    // Set indeterminate state on checkboxes for channels that exist via a different service. The indeterminate property cannot be set via HTML attributes -
    // it must be set via JavaScript after the elements are in the DOM.
    "    const switchCbs = document.querySelectorAll('.browse-channel-cb[data-original=\"switch\"]');",
    "    for(const sc of switchCbs) sc.indeterminate = true;",

    // Set the legend's indeterminate checkbox visual.
    "    const legendInd = document.querySelector('.browse-legend-indeterminate');",
    "    if(legendInd) legendInd.indeterminate = true;",

    // Attach event handlers programmatically to keep them scoped to the IIFE closure.
    "    const selectAllCb = document.getElementById('browse-select-all-cb');",
    "    if(selectAllCb) selectAllCb.addEventListener('change', function() { toggleBrowseSelectAll(this.checked); });",
    "    const searchInput = document.getElementById('browse-search');",
    "    if(searchInput) searchInput.addEventListener('input', filterBrowseChannels);",
    "    const channelCbs = document.querySelectorAll('.browse-channel-cb');",
    "    for(const cb of channelCbs) {",
    "      cb.addEventListener('change', function() { onBrowseCheckboxChange(this); });",
    "    }",

    // Show the apply button and update counts.
    "    browseWizard.show('browse-add-btn');",
    "    updateBrowseCount();",
    "  }",

    // Handle checkbox state changes. On uncheck, the visual depends on the channel's state: switch channels restore to indeterminate (they arrived that
    // way). Current channels show indeterminate if alternatives exist (channel persists elsewhere) or empty if not (channel will be disabled). New and
    // disabled channels stay empty on uncheck.
    "  function onBrowseCheckboxChange(cb) {",
    "    if(!cb.checked) {",
    "      const original = cb.getAttribute('data-original');",
    "      const hasAlt = cb.getAttribute('data-has-alternatives') === 'true';",
    "      if((original === 'switch') || ((original === 'current') && hasAlt)) {",
    "        cb.indeterminate = true;",
    "      }",
    "    }",
    "    updateBrowseCount();",
    "  }",

    // Toggle all actionable checkboxes. Select-all checks all channels and clears indeterminate. Deselect-all unchecks new and disabled channels, and restores
    // switch channels and current channels with alternatives to indeterminate (indicating the channel exists but is not selected for this service).
    "  function toggleBrowseSelectAll(checked) {",
    "    const cbs = document.querySelectorAll('.browse-channel-cb');",
    "    for(const cb of cbs) {",
    "      const original = cb.getAttribute('data-original');",
    "      const row = cb.closest('.browse-channel-item');",
    "      if(row && row.style.display === 'none') continue;",
    "      if(checked) {",
    "        cb.checked = true;",
    "        cb.indeterminate = false;",
    "      } else {",
    "        const hasAlt = cb.getAttribute('data-has-alternatives') === 'true';",
    "        cb.checked = false;",
    "        cb.indeterminate = (original === 'switch') || ((original === 'current') && hasAlt);",
    "      }",
    "    }",
    "    updateBrowseCount();",
    "  }",

    // Filter the channel list by search text. Hides rows whose channel name does not contain the search term.
    "  function filterBrowseChannels() {",
    "    const query = (document.getElementById('browse-search').value || '').toLowerCase();",
    "    const rows = document.querySelectorAll('.browse-channel-item');",
    "    for(const row of rows) {",
    "      const name = row.getAttribute('data-name') || '';",
    "      row.style.display = (!query || name.includes(query)) ? '' : 'none';",
    "    }",
    "  }",

    // Update the apply button text with categorized action counts. Computes add, switch, and remove counts based on checkbox state vs data-original.
    "  function updateBrowseCount() {",
    "    const cbs = document.querySelectorAll('.browse-channel-cb');",
    "    let addCount = 0;",
    "    let switchCount = 0;",
    "    let removeCount = 0;",
    "    for(const cb of cbs) {",
    "      const original = cb.getAttribute('data-original');",
    "      const row = cb.closest('.browse-channel-item');",
    "      if(row && row.style.display === 'none') continue;",
    "      if((original === 'new' || original === 'disabled') && cb.checked) addCount++;",
    "      if(original === 'switch' && cb.checked && !cb.indeterminate) switchCount++;",
    "      if(original === 'current' && !cb.checked) removeCount++;",
    "    }",
    "    const btn = document.getElementById('browse-add-btn');",
    "    const total = addCount + switchCount + removeCount;",
    "    const parts = [];",
    "    if(addCount > 0) parts.push('add ' + addCount);",
    "    if(switchCount > 0) parts.push('switch ' + switchCount);",
    "    if(removeCount > 0) parts.push('remove ' + removeCount);",
    "    btn.textContent = total > 0 ? 'Apply (' + parts.join(', ') + ')' : 'Apply';",
    "    btn.disabled = total === 0;",

    // Update select-all checkbox state.
    "    const allCbs = document.querySelectorAll('.browse-channel-cb');",
    "    let allChecked = true;",
    "    let visibleCount = 0;",
    "    for(const ac of allCbs) {",
    "      const r = ac.closest('.browse-channel-item');",
    "      if(r && r.style.display === 'none') continue;",
    "      visibleCount++;",
    "      if(!ac.checked) allChecked = false;",
    "    }",
    "    const selectAll = document.getElementById('browse-select-all-cb');",
    "    if(selectAll) selectAll.checked = (visibleCount > 0) && allChecked;",
    "  }",

    // Submit channel changes via the modify endpoint. Collects the applicable action for each visible checkbox by comparing its checked/indeterminate state
    // to data-original: add (new channels checked), enable (disabled channels checked), switch (switched-to channels checked), or remove (current channels
    // unchecked). Each entry includes an action field so the server can handle them appropriately.
    "  window.submitBrowseChannels = () => {",
    "    const cbs = document.querySelectorAll('.browse-channel-cb');",
    "    const guideUrl = browseGuideUrls[browseWizard.state.slug] || '';",
    "    const entries = [];",
    "    for(const cb of cbs) {",
    "      const original = cb.getAttribute('data-original');",
    "      const row = cb.closest('.browse-channel-item');",
    "      if(row && row.style.display === 'none') continue;",
    "      let action = null;",
    "      if(original === 'new' && cb.checked) action = 'add';",
    "      if(original === 'disabled' && cb.checked) action = 'enable';",
    "      if(original === 'switch' && cb.checked && !cb.indeterminate) action = 'switch';",
    "      if(original === 'current' && !cb.checked) action = 'remove';",
    "      if(!action) continue;",
    "      const entry = {",
    "        action: action,",
    "        canonicalKey: cb.getAttribute('data-canonical') || '',",
    "        channelSelector: cb.getAttribute('data-selector'),",
    "        name: cb.getAttribute('data-name'),",
    "        serviceSlug: browseWizard.state.slug,",
    "        url: guideUrl",
    "      };",
    "      const sid = cb.getAttribute('data-station-id');",
    "      if(sid) entry.stationId = sid;",
    "      entries.push(entry);",
    "    }",
    "    if(entries.length === 0) return;",

    // Disable the button to prevent double submission.
    "    const btn = document.getElementById('browse-add-btn');",
    "    btn.disabled = true;",
    "    btn.textContent = 'Applying...';",

    "    (async () => {",
    "      try {",
    "        const res = await fetch('/config/channels/modify', {",
    "          body: JSON.stringify({ channels: entries }),",
    "          headers: { 'Content-Type': 'application/json' },",
    "          method: 'POST'",
    "        });",
    "        const data = await res.json();",
    "        if(data.success) {",
    "          browseWizard.close();",
    "          showToast(data.message || 'Channels added.', 'success');",
    "          if(data.patch) { channelTable.applyPatch(data.patch); }",
    "          if(data.serviceWarning && typeof showServiceFilterWarning === 'function') { showServiceFilterWarning(data.serviceWarning); }",
    "        } else {",
    "          btn.disabled = false;",
    "          updateBrowseCount();",
    "          showToast('Failed to add channels: ' + extractErrorMessage(data, 'Unknown error.'), 'error');",
    "        }",
    "      } catch(err) {",
    "        console.error('Browse channels request failed.', err);",
    "        btn.disabled = false;",
    "        updateBrowseCount();",
    "        showToast('Failed to add channels.', 'error');",
    "      }",
    "    })();",
    "  };",

    // Read embedded service data for the setup wizard. Each entry includes domain, iconUrl, displayName, tag, and enabled state from the server.
    "  let setupServices = [];",
    "  try {",
    "    const spEl = document.getElementById('setup-services-data');",
    "    if(spEl) setupServices = JSON.parse(spEl.textContent || '[]');",
    "  } catch(e) { console.warn('Embedded setup services data failed to parse.', e); }",

    // Validate the current setup step. Step 1 collects selected services, validates at least one is selected, and saves the service filter to the server
    // asynchronously. Returns a Promise that resolves to an error string or empty string. Step 2+ always passes (no validation needed).
    "  async function validateSetupStep(step) {",
    "    if(step === 1) {",
    "      const selected = [];",
    "      const cbs = document.querySelectorAll('.setup-provider-cb:checked');",
    "      for(const cb of cbs) selected.push(cb.value);",
    "      if(selected.length === 0) return 'Select at least one service.';",
    "      setupWizard.state.selectedServices = selected;",
    "      setupWizard.state.authIndex = 0;",
    "      try {",
    "        await fetch('/config/service-filter', {",
    "          body: JSON.stringify({ enabledServices: selected }),",
    "          headers: { 'Content-Type': 'application/json' },",
    "          method: 'POST'",
    "        });",
    "        return '';",
    "      } catch(e) { return 'Failed to save service selection.'; }",
    "    }",
    "    return '';",
    "  }",

    // Service Setup wizard. Uses the shared wizard controller for step navigation and indicator updates. The state object tracks selected services and
    // the current auth index for the sequential sign-in flow.
    "  const setupWizard = createWizardController({",
    "    contentId: 'setup-content',",
    "    errorId: 'setup-error',",
    "    modalId: 'setup-modal',",
    "    onClose: () => {",
    "      if(setupWizard.getStep() === 2) { fetch('/auth/done', { method: 'POST' }).catch((err) => { console.warn('Auth done notification failed.', err); }); }",
    "    },",
    "    onRender: renderSetupStep,",
    "    onValidate: validateSetupStep,",
    "    stepCount: 3,",
    "    stepsId: 'setup-steps',",
    "    titleId: 'setup-title'",
    "  });",

    // Open the setup wizard and render the first step. Pre-populate selected services from the embedded enabled state so re-running the wizard shows the
    // current service filter as pre-checked.
    "  window.openSetupWizard = () => {",
    "    const preSelected = setupServices.filter((p) => p.enabled).map((p) => p.tag);",
    "    setupWizard.state = { selectedServices: preSelected, authIndex: 0 };",
    "    setupWizard.open();",
    "  };",

    // Skip the entire setup flow and mark as completed.
    "  window.skipSetup = async () => {",
    "    try { await fetch('/config/channels/setup-completed', { headers: { 'Content-Type': 'application/json' }, method: 'POST' }); }",
    "    catch(e) { console.warn('Setup completion failed to persist on skip.', e); }",
    "    setupWizard.close();",
    "  };",

    // Authenticate the current service in step 2. Opens the browser and shows a waiting prompt.
    "  async function setupAuthService() {",
    "    const slug = setupWizard.state.selectedServices[setupWizard.state.authIndex];",
    "    const svc = setupServices.find((p) => p.tag === slug);",
    "    const url = svc && svc.domain ? 'https://' + svc.domain + '/' : '';",
    "    if(!url) { setupAdvanceAuth(); return; }",
    "    try {",
    "      const res = await fetch('/auth/login', {",
    "        body: JSON.stringify({ url: url }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(data.success) renderSetupAuthWaiting();",
    "      else showToast('Failed to start login: ' + extractErrorMessage(data, 'Unknown error.'), 'error');",
    "    } catch(e) { console.error('Login start request failed.', e); showToast('Failed to start login.', 'error'); }",
    "  }",

    // Mark the current service auth as done and advance to the next.
    "  function setupAuthDone() {",
    "    fetch('/auth/done', { method: 'POST' }).catch((err) => { console.warn('Auth done notification failed.', err); });",
    "    setupAdvanceAuth();",
    "  }",

    // Skip the current service auth and advance.
    "  function setupAuthSkip() {",
    "    fetch('/auth/done', { method: 'POST' }).catch((err) => { console.warn('Auth done notification failed.', err); });",
    "    setupAdvanceAuth();",
    "  }",

    // Advance to the next service or to step 3 if all are done.
    "  function setupAdvanceAuth() {",
    "    setupWizard.state.authIndex++;",
    "    if(setupWizard.state.authIndex >= setupWizard.state.selectedServices.length) {",
    "      setupWizard.next();",
    "    } else {",
    "      renderSetupStep(setupWizard.getStep());",
    "    }",
    "  }",

    // Finish the setup wizard. Mark as completed and refresh the channel table.
    "  window.finishSetup = async () => {",
    "    try {",
    "      const res = await fetch('/config/channels/setup-completed', { headers: { 'Content-Type': 'application/json' }, method: 'POST' });",
    "      const data = await res.json();",
    "      setupWizard.close();",
    "      if(data.patch) { channelTable.applyPatch(data.patch); }",
    "    } catch(err) { console.error('Setup finish request failed.', err); setupWizard.close(); }",
    "  };",

    // Render the auth waiting state - shows a message while the user authenticates in Chrome. The Done and Skip buttons carry data-click-action attributes; the
    // project-wide dispatcher routes the clicks through the registerAction handlers installed below.
    "  function renderSetupAuthWaiting() {",
    "    const slug = setupWizard.state.selectedServices[setupWizard.state.authIndex];",
    "    const svc = setupServices.find((p) => p.tag === slug);",
    "    const label = svc ? svc.displayName : slug;",
    "    const content = document.getElementById('setup-content');",
    "    content.innerHTML = '<div class=\"wizard-spinner\">Complete authentication for ' + escapeHtml(label) +",
    "      ' in the Chrome browser window...</div>' +",
    "      '<div class=\"wizard-step-centered-compact\">' +",
    "      '<button type=\"button\" class=\"btn btn-primary\" data-click-action=\"" + ACTIONS.authDone + "\">Done</button> ' +",
    "      '<button type=\"button\" class=\"btn btn-secondary\" data-click-action=\"" + ACTIONS.authSkip + "\">Skip</button></div>';",
    "  }",

    // Render the current setup step content and update navigation buttons. The controller handles step indicator updates and error clearing.
    "  function renderSetupStep(step) {",
    "    const content = document.getElementById('setup-content');",

    // Show/hide navigation buttons based on the current step.
    "    if(step > 1) { setupWizard.show('setup-back'); } else { setupWizard.hide('setup-back'); }",
    "    if(step < 3) { setupWizard.show('setup-next'); setupWizard.show('setup-skip'); }",
    "    else { setupWizard.hide('setup-next'); setupWizard.hide('setup-skip'); }",
    "    if(step === 3) { setupWizard.show('setup-finish'); } else { setupWizard.hide('setup-finish'); }",

    "    let html = '';",

    // Step 1: Service selection with multi-select cards.
    "    if(step === 1) {",
    "      html += '<p class=\"wizard-hint\">Select the streaming services you subscribe to. " +
      "This determines which channels are available in your lineup.</p>';",
    "      html += '<div class=\"wizard-provider-grid\">';",
    "      for(const p of setupServices) {",
    "        const checked = setupWizard.state.selectedServices.includes(p.tag) ? ' checked' : '';",
    "        html += '<label class=\"wizard-provider-card\">';",
    "        html += '<input type=\"checkbox\" class=\"setup-provider-cb\" value=\"' + p.tag + '\"' + checked + '>';",
    // serviceIconHtml escapes its name argument internally, so displayName is passed raw; escaping it here too would double-encode.
    "        html += serviceIconHtml(p.domain || '', p.displayName, 'provider-icon', 'provider-icon-text', 'both', p.iconUrl || '');",
    "        html += '</label>';",
    "      }",
    "      html += '</div>';",
    "    }",

    // Step 2: Sequential authentication prompts.
    "    if(step === 2) {",
    "      const slug = setupWizard.state.selectedServices[setupWizard.state.authIndex];",
    "      const svc = setupServices.find((p) => p.tag === slug);",
    "      const label = svc ? svc.displayName : slug;",
    "      const total = setupWizard.state.selectedServices.length;",
    "      const current = setupWizard.state.authIndex + 1;",
    "      html += '<p class=\"wizard-hint\">Sign in to each service in the Chrome browser window. " +
      "PrismCast uses your login session to access live streams.</p>';",
    "      html += '<div class=\"wizard-step-centered\">';",
    "      html += '<p class=\"wizard-step-provider-name\">' + escapeHtml(label) + '</p>';",
    "      html += '<p class=\"wizard-step-provider-count\">Service ' + current + ' of ' + total + '</p>';",
    "      html += '<button type=\"button\" class=\"btn btn-primary\" data-click-action=\"" + ACTIONS.authStart + "\">Sign In</button> ';",
    "      html += '<button type=\"button\" class=\"btn btn-secondary\" data-click-action=\"" + ACTIONS.authSkip + "\">Skip</button>';",
    "      html += '</div>';",
    "    }",

    // Step 3: Summary and finish.
    "    if(step === 3) {",
    "      html += '<p class=\"wizard-hint\">Your services are ready. Click Finish to complete setup. " +
      "You can browse and manage channels anytime using the Browse Channels button.</p>';",
    "      html += '<div class=\"wizard-step-centered\">';",
    "      html += '<p class=\"wizard-step-summary\">Selected ' + setupWizard.state.selectedServices.length + ' service' +",
    "        (setupWizard.state.selectedServices.length === 1 ? '' : 's') + '.</p>';",
    "      html += '</div>';",
    "    }",

    "    content.innerHTML = html;",
    "  }",

    // Tag Management Modal.

    // Single function for applying tag mutation responses. Updates the tag manager modal body, the column header filter dropdown, the channel table patch, and shows
    // a toast. Exposed on window so both channels.ts and config.ts (bulkToggleTag) can use the same code path. No page reload needed. The server's message wins over
    // the caller's fallback so a mutation response can carry the playlist-reload hint; the fallback covers responses that carry no message.
    "  window.applyTagResponse = (data, toastMessage) => {",
    "    const contentDiv = document.getElementById('tag-manager-modal-content');",
    "    if(contentDiv && data.modalBody) { contentDiv.innerHTML = data.modalBody; }",
    "    const filterMenu = document.getElementById('tag-filter-menu');",
    "    if(filterMenu && data.filterContent) { filterMenu.innerHTML = data.filterContent; applyTagColumnFilter(); }",
    "    if(data.patch) { channelTable.applyPatch(data.patch); }",
    "    const toast = data.message || toastMessage;",
    "    if(toast && window.showToast) { window.showToast(toast); }",
    "  };",

    "  window.openTagManager = () => {",
    "    const modal = document.getElementById('tag-manager-modal');",
    "    if(modal) { modal.style.display = 'flex'; }",
    "  };",

    "  window.closeTagManager = () => {",
    "    const modal = document.getElementById('tag-manager-modal');",
    "    if(modal) { modal.style.display = 'none'; }",
    "  };",

    // Create a new tag via the API, then update the modal incrementally and show a toast.
    "  window.createTag = async () => {",
    "    const input = document.getElementById('tag-manager-input');",
    "    const errorDiv = document.getElementById('tag-manager-error');",
    "    const tag = input ? input.value.trim() : '';",
    "    if(!tag) return;",
    "    errorDiv.style.display = 'none';",
    "    try {",
    "      const res = await fetch('/config/tags', {",
    "        body: JSON.stringify({ tag }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(!data.success) {",
    "        errorDiv.textContent = extractErrorMessage(data, 'Failed to create tag.');",
    "        errorDiv.style.display = '';",
    "        return;",
    "      }",
    "      applyTagResponse(data, 'Tag created: ' + tag);",
    "    } catch(err) {",
    "      console.error('Tag creation request failed.', err);",
    "      errorDiv.textContent = 'Failed to create tag.';",
    "      errorDiv.style.display = '';",
    "    }",
    "  };",

    // Delete a tag via the API, then update the modal and channel table incrementally.
    "  window.deleteTag = async (tag) => {",
    "    try {",
    "      const res = await fetch('/config/tags/' + encodeURIComponent(tag), { method: 'DELETE' });",
    "      const data = await res.json();",
    "      if(!data.success) {",
    "        showToast(extractErrorMessage(data, 'Failed to delete tag.'), 'error');",
    "        return;",
    "      }",
    "      applyTagResponse(data, 'Tag deleted: ' + tag);",
    "    } catch(err) {",
    "      console.error('Tag deletion request failed.', err);",
    "      showToast('Failed to delete tag.', 'error');",
    "    }",
    "  };",

    // Restore a deleted predefined tag via the API, then update the modal and channel table incrementally.
    "  window.restoreTag = async (tag) => {",
    "    try {",
    "      const res = await fetch('/config/tags/restore', {",
    "        body: JSON.stringify({ tag }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(!data.success) {",
    "        showToast(extractErrorMessage(data, 'Failed to restore tag.'), 'error');",
    "        return;",
    "      }",
    "      applyTagResponse(data, 'Tag restored: ' + tag);",
    "    } catch(err) {",
    "      console.error('Tag restore request failed.', err);",
    "      showToast('Failed to restore tag.', 'error');",
    "    }",
    "  };",

    // Tag Column Filter - client-side view filter that shows/hides rows based on their data-channel-tags attribute. Transient (not persisted, resets on page load).
    // All tag checkboxes start checked (show all). Unchecking a tag hides rows that don't have ANY of the remaining checked tags.

    "  window.applyTagColumnFilter = () => {",
    "    const checkboxes = document.querySelectorAll('.tag-filter-checkbox');",
    "    const checkedTags = [];",
    "    let allChecked = true;",
    "    for(const checkbox of checkboxes) {",
    "      if(checkbox.checked) { checkedTags.push(checkbox.getAttribute('data-tag')); }",
    "      else { allChecked = false; }",
    "    }",
    "    const rows = document.querySelectorAll('tr[id^=\"display-row-\"]');",
    "    for(const row of rows) {",
    "      const editRow = document.getElementById(row.id.replace('display-row-', 'edit-row-'));",
    "      if(allChecked) {",
    "        row.classList.remove('tag-filtered');",
    "        if(editRow) editRow.classList.remove('tag-filtered');",
    "        continue;",
    "      }",
    "      const tags = row.getAttribute('data-channel-tags');",
    "      const channelTags = tags ? tags.split(',') : [];",
    "      const visible = channelTags.some((ct) => checkedTags.includes(ct));",
    "      row.classList.toggle('tag-filtered', !visible);",
    "      if(editRow) editRow.classList.toggle('tag-filtered', !visible);",
    "    }",

    // Show or hide the playlist hint icon based on filter state. When the filter is active, users can click the icon to see the corresponding playlist URL.
    "    const hintBtn = document.getElementById('playlist-hint-btn');",
    "    if(hintBtn) { hintBtn.style.display = allChecked ? 'none' : ''; }",

    // Update the toggle label to reflect the current state: "Show All" when some are unchecked, "Show None" when all are checked.
    "    const toggle = document.getElementById('tag-filter-toggle');",
    "    if(toggle) { toggle.textContent = allChecked ? 'Show None' : 'Show All'; }",
    "  };",

    // Toggle all tag filter checkboxes. When all are checked, uncheck all. When any are unchecked, check all. Matches the browse modal's Select All pattern.
    "  window.toggleTagColumnFilter = () => {",
    "    const checkboxes = document.querySelectorAll('.tag-filter-checkbox');",
    "    let allChecked = true;",
    "    for(const checkbox of checkboxes) { if(!checkbox.checked) { allChecked = false; break; } }",
    "    for(const checkbox of checkboxes) { checkbox.checked = !allChecked; }",
    "    applyTagColumnFilter();",
    "  };",

    // Playlist hint popover. Builds the content dynamically from the current filter state and shows it using the existing dropdown portal pattern. Uses whichever
    // form (include or exclude) produces a shorter URL. The label names the specific tags so the user sees exactly what the URL produces.
    "  window.showPlaylistHint = (btn) => {",
    "    const checkboxes = document.querySelectorAll('.tag-filter-checkbox');",
    "    const checked = [];",
    "    const unchecked = [];",
    "    for(const checkbox of checkboxes) {",
    "      const tag = checkbox.getAttribute('data-tag');",
    "      if(checkbox.checked) { checked.push(tag); }",
    "      else { unchecked.push(tag); }",
    "    }",
    "    const useExclude = unchecked.length < checked.length;",
    "    const tagParam = useExclude ? unchecked.map((t) => '-' + t).join(',') : checked.join(',');",
    "    const url = location.origin + '/playlist?tag=' + tagParam;",
    "    const label = useExclude ? 'all channels except those tagged <strong>' + unchecked.map((t) => escapeHtml(t)).join(', ') + '</strong>'",
    "      : 'channels tagged <strong>' + checked.map((t) => escapeHtml(t)).join(', ') + '</strong>';",
    "    toggleDropdown(btn, { onOpen: (menu) => {",
    "      menu.innerHTML = '<div class=\"playlist-hint-content\">' +",
    "        '<p>Playlist URL for Channels DVR: ' + label + '.</p>' +",
    "        '<div class=\"playlist-hint-url\">' +",
    "        '<code>' + escapeHtml(url) + '</code>' +",
    "        '<button type=\"button\" class=\"btn btn-primary btn-sm\" data-click-action=\"" + ACTIONS.copyPlaylistHintUrl + "\">Copy</button>' +",
    "        '</div></div>';",
    "    }});",
    "  };",

    // Copy the playlist hint URL to the clipboard. Thin wrapper that reads the URL from the popover's code element and delegates to the shared copyToClipboard utility.
    "  window.copyPlaylistHintUrl = () => {",
    "    const code = document.querySelector('.playlist-hint-content code');",
    "    if(code) { copyToClipboard(code.textContent, 'Playlist URL copied to clipboard.'); }",
    "  };",

    // Inline tag rename - replaces the tag pill with an input field. The original span is saved so it can be restored on cancel or error without a page reload.
    "  window.startTagRename = (span, oldTag) => {",
    "    const originalSpan = span;",
    "    const input = document.createElement('input');",
    "    input.type = 'text';",
    "    input.value = oldTag;",
    "    input.className = 'tag-rename-input';",
    "    input.maxLength = 30;",
    "    let submitted = false;",
    "    function restore() { if(input.parentNode) input.replaceWith(originalSpan); }",
    "    async function submit() {",
    "      if(submitted) return;",
    "      submitted = true;",
    "      const newTag = input.value.trim();",
    "      if(!newTag || (newTag === oldTag)) { restore(); return; }",
    "      try {",
    "        const res = await fetch('/config/tags/rename', {",
    "          body: JSON.stringify({ newTag, oldTag }),",
    "          headers: { 'Content-Type': 'application/json' },",
    "          method: 'POST'",
    "        });",
    "        const data = await res.json();",
    "        if(!data.success) {",
    "          restore();",
    "          showToast(extractErrorMessage(data, 'Failed to rename tag.'), 'error');",
    "          return;",
    "        }",
    "        applyTagResponse(data, 'Tag renamed: ' + oldTag + ' \\u2192 ' + newTag);",
    "      } catch(err) {",
    "        console.error('Tag rename request failed.', err);",
    "        restore();",
    "        showToast('Failed to rename tag.', 'error');",
    "      }",
    "    }",
    "    input.onkeydown = (e) => {",
    "      if(e.key === 'Enter') { e.preventDefault(); submit(); }",
    "      if(e.key === 'Escape') { e.preventDefault(); restore(); }",
    "    };",
    "    input.onblur = () => { submit(); };",
    "    span.replaceWith(input);",
    "    input.focus();",
    "    input.select();",
    "  };",

    // Auto-show the setup wizard on first visit if setupCompleted is false.
    "  const setupModal = document.getElementById('setup-modal');",
    "  if(setupModal && setupModal.getAttribute('data-setup-completed') === 'false') {",
    "    openSetupWizard();",
    "  }",

    // Process channel logos and service icons on page load. These shared functions are also called after DOM mutations (row insertion, chip rebuild) to ensure
    // dynamically added elements get the same icon rendering as the initial server-rendered content.
    "  channelTable.processLogos();",
    "  processServiceDisplays();",

    // Initialize channels subtab on load: hash > localStorage > default.
    "  initSubtab({",
    "    btnSelector: '.channels-subtab-btn',",
    "    dataAttr: 'data-channels-subtab',",
    "    hashVar: window.initialChannelsHashSubtab,",
    "    storageKey: 'prismcast-channels-subtab',",
    "    switchFn: switchChannelsSubtab",
    "  });",

    /* Action registrations. Each binds an ACTIONS name to a window-exposed handler defined above; the project-wide dispatcher in shared.ts looks up the handler
     * by name when a click / change / keydown / submit event lands on a matching [data-<event>-action] element. Handlers express only the action's intent -
     * event mechanics (preventDefault, stopPropagation, dropdown close) live declaratively on the trigger element via the event-type-scoped data-<event>-prevent
     * -default, data-<event>-stop-propagation, and data-<event>-close-dropdown attributes that the dispatcher processes before the handler runs.
     */
    "  window.registerAction('" + ACTIONS.applyTagColumnFilter + "', () => applyTagColumnFilter());",
    "  window.registerAction('" + ACTIONS.authDone + "', () => setupAuthDone());",
    "  window.registerAction('" + ACTIONS.authSkip + "', () => setupAuthSkip());",
    "  window.registerAction('" + ACTIONS.authStart + "', () => setupAuthService());",
    "  window.registerAction('" + ACTIONS.checkSelectors + "', () => checkSelectors());",
    "  window.registerAction('" + ACTIONS.copyPlaylistHintUrl + "', () => copyPlaylistHintUrl());",
    "  window.registerAction('" + ACTIONS.closeExportModal + "', () => closeExportModal());",
    "  window.registerAction('" + ACTIONS.closeImportModal + "', () => closeImportModal());",
    "  window.registerAction('" + ACTIONS.closeTagManager + "', () => closeTagManager());",
    "  window.registerAction('" + ACTIONS.createTag + "', () => createTag());",
    /* Conditional preventDefault on a specific key. data-keydown-prevent-default would fire on every keystroke; only Enter should be canceled. The conditional
     * filtering logic lives in the handler since the dispatcher's modifier walk has no per-key scope.
     */
    "  window.registerAction('" + ACTIONS.createTagOnEnter + "', (target, event) => {",
    "    if(event.key === 'Enter') { event.preventDefault(); createTag(); }",
    "  });",
    "  window.registerAction('" + ACTIONS.deleteTag + "', (target) => deleteTag(target.dataset.tagName));",
    "  window.registerAction('" + ACTIONS.deleteUserProfile + "', (target) => deleteUserProfile(target.dataset.profileKey));",
    "  window.registerAction('" + ACTIONS.editUserProfile + "', (target) => editUserProfile(target.dataset.profileKey));",
    "  window.registerAction('" + ACTIONS.endProfileTest + "', () => endProfileTest());",
    "  window.registerAction('" + ACTIONS.executeExport + "', () => executeExport());",
    "  window.registerAction('" + ACTIONS.executeImport + "', () => executeImport());",
    "  window.registerAction('" + ACTIONS.finishSetup + "', () => finishSetup());",
    "  window.registerAction('" + ACTIONS.openBrowseModal + "', () => openBrowseModal());",
    "  window.registerAction('" + ACTIONS.openSetupWizard + "', () => openSetupWizard());",
    "  window.registerAction('" + ACTIONS.openTagManager + "', () => openTagManager());",
    "  window.registerAction('" + ACTIONS.openWizard + "', () => openWizard());",
    "  window.registerAction('" + ACTIONS.restoreTag + "', (target) => restoreTag(target.dataset.tagName));",
    "  window.registerAction('" + ACTIONS.saveProfile + "', (target) => saveProfile(target.dataset.withTest === 'true'));",
    "  window.registerAction('" + ACTIONS.showPlaylistHint + "', (target) => showPlaylistHint(target));",
    "  window.registerAction('" + ACTIONS.skipSetup + "', () => skipSetup());",
    "  window.registerAction('" + ACTIONS.startServiceExport + "', () => startServiceExport());",
    "  window.registerAction('" + ACTIONS.startServiceImport + "', () => startServiceImport());",
    "  window.registerAction('" + ACTIONS.startTagRename + "', (target) => startTagRename(target, target.dataset.tagName));",
    "  window.registerAction('" + ACTIONS.submitBrowseChannels + "', () => submitBrowseChannels());",
    "  window.registerAction('" + ACTIONS.toggleExportAll + "', (target) => toggleExportAll(target));",
    "  window.registerAction('" + ACTIONS.toggleTagColumnFilter + "', () => toggleTagColumnFilter());",

    "})();",
    "</script>"
  ].join("\n");
}
