/* Copyright(C) 2024-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * config.ts: Client-side JavaScript generator for the PrismCast configuration subtab.
 */
import { VIDEO_QUALITY_PRESETS } from "../../../config/presets.js";
import { isRunningAsService } from "../../../utils/index.js";

export function generateConfigSubtabScript(): string {

  // Build preset data for auto-filling bitrate and frame rate when preset changes. Viewport is derived server-side and not included here.
  const presetBlocks: string[] = [];

  for(const preset of VIDEO_QUALITY_PRESETS) {

    // Only include bitrate and frame rate, not viewport (viewport is derived from preset server-side).
    const bitrateValue = preset.values["streaming.videoBitsPerSecond"];
    const frameRateValue = preset.values["streaming.frameRate"];

    // Convert bitrate from bps to Mbps for display.
    const block = [
      "    '" + preset.id + "': {",
      "      'streaming-videoBitsPerSecond': " + String(bitrateValue / 1000000) + ",",
      "      'streaming-frameRate': " + String(frameRateValue),
      "    }"
    ].join("\n");

    presetBlocks.push(block);
  }

  // Pass service status to JavaScript for conditional messaging.
  const isService = isRunningAsService();

  return [
    "<script>",
    "(function() {",

    // Service mode flag for conditional UI behavior.
    "  const isServiceMode = " + String(isService) + ";",

    // Preset values for auto-filling bitrate and frame rate.
    "  const presetValues = {",
    presetBlocks.join(",\n"),
    "  };",

    // When quality preset changes, auto-fill bitrate and frame rate with preset values.
    "  function onPresetChange(presetId) {",
    "    const values = presetValues[presetId];",
    "    if(!values) return;",
    "    for(const [ inputId, value ] of Object.entries(values)) {",
    "      const input = document.getElementById(inputId);",
    "      if(input) {",
    "        input.value = value;",
    "        input.dispatchEvent(new Event('input', { bubbles: true }));",
    "      }",
    "    }",
    "  }",

    // Hint appended to success toasts when a channel operation changes M3U playlist content that Channels DVR consumes.
    "  const PLAYLIST_HINT = ' Reload the playlist in Channels DVR to see this change.';",

    // Pending-toast helpers. sessionStorage access is wrapped here so private browsing mode does not crash showToastAfterReload or the page-load consumer.
    // The producer serializes the toast, the consumer reads and removes it in one call.
    "  function setPendingToast(message, type) {",
    "    try { sessionStorage.setItem('pendingToast', JSON.stringify({ message: message, type: type || 'success' })); }",
    "    catch(e) {}",
    "  }",
    "  function consumePendingToast() {",
    "    try {",
    "      const raw = sessionStorage.getItem('pendingToast');",
    "      if(!raw) return null;",
    "      sessionStorage.removeItem('pendingToast');",
    "      return JSON.parse(raw);",
    "    } catch(e) { console.warn('Pending toast data failed to read or parse.', e); return null; }",
    "  }",

    // Queue a toast to appear after the next page reload.
    "  function showToastAfterReload(message, type) {",
    "    setPendingToast(message, type);",
    "    location.reload();",
    "  }",

    // Interval handle for restart polling.
    "  let restartPollInterval = null;",

    // Track whether a restart is pending (deferred due to active streams).
    "  let pendingRestart = false;",

    // Show the pending restart dialog when streams are active.
    "  function showPendingRestartDialog(streamCount) {",
    "    pendingRestart = true;",
    "    document.getElementById('restart-stream-count').textContent = streamCount;",
    "    document.getElementById('restart-dialog').style.display = 'flex';",
    "    updateRestartDialogStatus();",
    "  }",

    // Update the restart dialog when stream count changes. Exposed on window so the status script's streamRemoved handler can trigger it across script blocks.
    "  function updateRestartDialogStatus() {",
    "    const count = Object.keys(streamData).length;",
    "    document.getElementById('restart-stream-count').textContent = count;",
    "    if((count === 0) && pendingRestart) {",
    "      pendingRestart = false;",
    "      document.getElementById('restart-dialog').style.display = 'none';",
    "      triggerRestart();",
    "    }",
    "  }",
    "  window.updateRestartDialogStatus = updateRestartDialogStatus;",

    // Cancel the pending restart.
    "  window.cancelPendingRestart = () => {",
    "    pendingRestart = false;",
    "    document.getElementById('restart-dialog').style.display = 'none';",
    "    showToast('Restart cancelled. Changes will apply on next restart.', 'info');",
    "  };",

    // Force immediate restart despite active streams.
    "  window.forceRestart = async () => {",
    "    pendingRestart = false;",
    "    document.getElementById('restart-dialog').style.display = 'none';",
    "    try {",
    "      const res = await fetch('/config/restart-now', { method: 'POST' });",
    "      if(res.ok) {",
    "        waitForServerRestart();",
    "      } else {",
    "        const data = await res.json();",
    "        throw new Error(data.message || 'Restart failed');",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to restart: ' + err.message, 'error');",
    "    }",
    "  };",

    // Trigger restart (called when streams reach 0).
    "  async function triggerRestart() {",
    "    try {",
    "      const res = await fetch('/config/restart-now', { method: 'POST' });",
    "      if(res.ok) {",
    "        waitForServerRestart();",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to trigger restart. Please restart manually.', 'error');",
    "    }",
    "  }",

    // Wait for server restart by polling /health, then reload.
    "  function waitForServerRestart() {",
    "    let attempts = 0;",
    "    const maxAttempts = 30;",
    "    showToast('Restarting server...', 'info', 0);",
    "    if(restartPollInterval) { clearInterval(restartPollInterval); }",
    "    restartPollInterval = setInterval(async () => {",
    "      attempts++;",
    "      try {",
    "        const res = await fetch('/health');",
    "        if(res.ok) {",
    "          clearInterval(restartPollInterval);",
    "          restartPollInterval = null;",
    "          showToastAfterReload('Server restarted.', 'success');",
    "        }",
    "      } catch(err) {",
    "        if(attempts >= maxAttempts) {",
    "          clearInterval(restartPollInterval);",
    "          restartPollInterval = null;",
    "          showToast('Server did not restart within 30 seconds. Please check the server manually.', 'error');",
    "        }",
    "      }",
    "    }, 1000);",
    "  }",

    // Escape HTML entities in text for safe display.
    "  function escapeHtmlText(text) {",
    "    const div = document.createElement('div');",
    "    div.textContent = text;",
    "    return div.innerHTML;",
    "  }",

    // Open the changelog modal and fetch content dynamically. Also checks whether an upgrade button should be shown.
    "  window.openChangelogModal = async () => {",
    "    const modal = document.getElementById('changelog-modal');",
    "    if(!modal) return;",
    "    const title = modal.querySelector('.changelog-title');",
    "    const loading = modal.querySelector('.changelog-loading');",
    "    const content = modal.querySelector('.changelog-content');",
    "    const error = modal.querySelector('.changelog-error');",
    "    const upgradeBtn = document.getElementById('changelog-upgrade-btn');",
    "    modal.style.display = 'flex';",
    "    loading.style.display = 'block';",
    "    content.style.display = 'none';",
    "    error.style.display = 'none';",
    "    if(upgradeBtn) upgradeBtn.style.display = 'none';",
    "    try {",
    "      const res = await fetch('/version/changelog');",
    "      const data = await res.json();",
    "      loading.style.display = 'none';",
    "      title.textContent = \"What's new in v\" + data.displayVersion;",
    "      if(data.items && (data.items.length > 0)) {",
    "        let html = '<ul class=\"changelog-list\">';",
    "        for(const item of data.items) {",
    "          html += '<li>' + escapeHtmlText(item) + '</li>';",
    "        }",
    "        html += '</ul>';",
    "        content.innerHTML = html;",
    "        content.style.display = 'block';",
    "      } else {",
    "        error.style.display = 'block';",
    "      }",
    "      if(data.updateAvailable && upgradeBtn) { upgradeBtn.style.display = ''; }",
    "    } catch(err) {",
    "      loading.style.display = 'none';",
    "      error.style.display = 'block';",
    "    }",
    "  };",

    // Close the changelog modal.
    "  window.closeChangelogModal = () => {",
    "    const modal = document.getElementById('changelog-modal');",
    "    if(modal) { modal.style.display = 'none'; }",
    "  };",

    // Start the upgrade process from the changelog modal. Fetches upgrade info, confirms with the user if there are active streams, then executes the upgrade.
    "  window.startUpgrade = async () => {",
    "    try {",
    "      const infoRes = await fetch('/upgrade/info');",
    "      const info = await infoRes.json();",
    "      if(!info.upgradeable) {",
    "        closeChangelogModal();",
    "        const msg = info.method === 'docker'",
    "          ? 'Docker containers cannot be upgraded in-place. Pull the latest image and recreate the container.'",
    "          : 'Manual upgrade required: ' + info.upgradeCommand;",
    "        showToast(msg, 'info', 8000);",
    "        return;",
    "      }",
    "      const streamCount = Object.keys(streamData).length;",
    "      if(streamCount > 0) {",
    "        if(!confirm('There are ' + streamCount + ' active stream(s). Upgrading will interrupt them. Continue?')) return;",
    "      }",
    "      closeChangelogModal();",
    "      showToast('Upgrading PrismCast...', 'info', 0);",
    "      const upgradeRes = await fetch('/upgrade', { method: 'POST' });",
    "      const result = await upgradeRes.json();",
    "      if(result.success && result.willRestart) {",
    "        waitForServerRestart();",
    "      } else if(result.success) {",
    "        showToast('Upgrade complete. Please restart PrismCast manually.', 'success', 8000);",
    "      } else {",
    "        showToast('Upgrade failed: ' + result.message, 'error');",
    "      }",
    "    } catch(err) {",
    "      showToast('Upgrade failed: ' + err.message, 'error');",
    "    }",
    "  };",

    // Check for updates manually. Updates the version link in-place when a new version is found.
    "  window.checkForUpdates = async () => {",
    "    const btn = document.querySelector('.version-check');",
    "    if(!btn || btn.classList.contains('checking')) return;",
    "    btn.classList.add('checking');",
    "    try {",
    "      const res = await fetch('/version/check', { method: 'POST' });",
    "      const data = await res.json();",
    "      btn.classList.remove('checking');",
    "      if(data.updateAvailable && data.latestVersion) {",
    "        const link = document.querySelector('.version-container .version');",
    "        if(link && !link.classList.contains('version-update')) {",
    "          link.textContent = 'v' + data.currentVersion + ' \\u2192 v' + data.latestVersion;",
    "          link.classList.add('version-update');",
    "        }",
    "      } else {",
    "        btn.classList.add('up-to-date');",
    "        setTimeout(() => { btn.classList.remove('up-to-date'); }, 2000);",
    "      }",
    "    } catch(err) {",
    "      btn.classList.remove('checking');",
    "      btn.classList.add('check-error');",
    "      setTimeout(() => { btn.classList.remove('check-error'); }, 2000);",
    "    }",
    "  };",

    // Clear all field error indicators.
    "  function clearFieldErrors() {",
    "    const errorInputs = document.querySelectorAll('.form-input.error, .form-select.error');",
    "    for(const errorInput of errorInputs) {",
    "      errorInput.classList.remove('error');",
    "    }",
    "    const errorMsgs = document.querySelectorAll('.form-error.dynamic');",
    "    for(const errorMsg of errorMsgs) {",
    "      errorMsg.remove();",
    "    }",
    "  }",

    // Display field-level errors from server response.
    "  function displayFieldErrors(errors) {",
    "    for(const [ path, message ] of Object.entries(errors)) {",
    "      const inputId = path.replaceAll('.', '-');",
    "      const input = document.getElementById(inputId);",
    "      if(input) {",
    "        input.classList.add('error');",
    "        const errorDiv = document.createElement('div');",
    "        errorDiv.className = 'form-error dynamic';",
    "        errorDiv.textContent = message;",
    "        input.closest('.form-group').appendChild(errorDiv);",
    "      }",
    "    }",
    "  }",

    // Set a form input's value, handling checkbox and standard input types uniformly.
    "  function setInputValue(input, value) {",
    "    if(input.type === 'checkbox') {",
    "      input.checked = value === 'true';",
    "    } else {",
    "      input.value = value;",
    "    }",
    "    if(input.hasAttribute('data-checkbox-list')) {",
    "      const values = JSON.parse(value || '[]');",
    "      const grid = input.closest('.form-group').querySelector('.checkbox-list-grid');",
    "      if(grid) {",
    "        const cbs = grid.querySelectorAll('input[type=\"checkbox\"]');",
    "        for(const cb of cbs) {",
    "          cb.checked = values.includes(cb.value);",
    "        }",
    "      }",
    "    }",
    "  }",

    // Get a form input's current value as a string, handling checkbox and standard input types uniformly.
    "  function getInputValue(input) {",
    "    return input.type === 'checkbox' ? String(input.checked) : input.value;",
    "  }",

    // Toggle dependent fields when a boolean checkbox changes. Fields with data-depends-on are visually greyed out and removed from the tab order when the
    // referenced checkbox is unchecked. This function is defined at the top level so that both event handlers and reset functions can call it.
    "  function updateDependentFields(checkboxId) {",
    "    const checkbox = document.getElementById(checkboxId);",
    "    if(!checkbox) return;",
    "    const dependents = document.querySelectorAll('[data-depends-on=\"' + checkboxId + '\"]');",
    "    for(const dependent of dependents) {",
    "      if(checkbox.checked) {",
    "        dependent.classList.remove('depends-disabled');",
    "      } else {",
    "        dependent.classList.add('depends-disabled');",
    "      }",
    "      const depInputs = dependent.querySelectorAll('input:not([type=\"hidden\"]), select');",
    "      for(const depInput of depInputs) {",
    "        depInput.tabIndex = checkbox.checked ? 0 : -1;",
    "      }",
    "    }",
    "  }",

    // Update modified indicators for a single input.
    "  function updateModifiedIndicator(input) {",
    "    const defaultVal = input.getAttribute('data-default');",
    "    const currentVal = getInputValue(input);",
    "    const formGroup = input.closest('.form-group');",
    "    if(!formGroup) return;",
    "    const isModified = currentVal !== defaultVal;",
    "    const dot = formGroup.querySelector('.modified-dot');",
    "    const resetBtn = formGroup.querySelector('.btn-reset');",
    "    if(isModified) {",
    "      formGroup.classList.add('modified');",
    "      if(!dot) {",
    "        const label = formGroup.querySelector('.form-label');",
    "        if(label) {",
    "          const newDot = document.createElement('span');",
    "          newDot.className = 'modified-dot';",
    "          newDot.title = 'Modified from default';",
    "          label.insertBefore(newDot, label.firstChild);",
    "        }",
    "      }",
    "      if(!resetBtn) {",
    "        const row = formGroup.querySelector('.form-row');",
    "        if(row) {",
    "          const path = input.getAttribute('name');",
    "          const btn = document.createElement('button');",
    "          btn.type = 'button';",
    "          btn.className = 'btn-reset';",
    "          btn.title = 'Reset to default';",
    "          btn.setAttribute('aria-label', 'Reset to default');",
    "          btn.innerHTML = '&#8635;';",
    "          btn.onclick = () => { resetSetting(path); };",
    "          row.appendChild(btn);",
    "        }",
    "      }",
    "    } else {",
    "      formGroup.classList.remove('modified');",
    "      if(dot) dot.remove();",
    "      if(resetBtn) resetBtn.remove();",
    "    }",
    "  }",

    // Reset a single setting to its default value (client-side only). Dispatches both input and change events to match browser behavior: input for validation and
    // modified indicator updates, change for cascade handlers (e.g., preset dropdown updating bitrate and frame rate fields).
    "  window.resetSetting = (path) => {",
    "    const inputId = path.replaceAll('.', '-');",
    "    const input = document.getElementById(inputId);",
    "    if(!input) return;",
    "    const defaultVal = input.getAttribute('data-default');",
    "    if(defaultVal !== null) {",
    "      setInputValue(input, defaultVal);",
    "      input.dispatchEvent(new Event('input', { bubbles: true }));",
    "      input.dispatchEvent(new Event('change', { bubbles: true }));",
    "    }",
    "  };",

    // Reset all settings in a tab to defaults (client-side only). Works for both settings and advanced tabs.
    "  window.resetTabToDefaults = (tabId) => {",
    "    if(!confirm('Reset all settings in this tab to defaults?')) return;",
    "    const panel = document.getElementById('subtab-' + tabId);",
    "    if(!panel) return;",
    "    const inputs = panel.querySelectorAll('input[data-default], select[data-default]');",
    "    for(const input of inputs) {",
    "      if(!input.disabled) {",
    "        setInputValue(input, input.getAttribute('data-default'));",
    "        updateModifiedIndicator(input);",
    "      }",
    "    }",
    "    const cbInputs = panel.querySelectorAll('input[type=\"checkbox\"][data-default]');",
    "    for(const cbInput of cbInputs) {",
    "      if(!cbInput.disabled) {",
    "        updateDependentFields(cbInput.id);",
    "      }",
    "    }",
    "    showToast('Settings reset to defaults. Click ' + (isServiceMode ? 'Save & Restart' : 'Save Settings') + ' to apply changes.', 'info');",
    "  };",

    // Read the advanced section expansion state from localStorage. Returns the parsed object or {} if missing or corrupted. Single source of truth for
    // reading this key — used by both toggleSection (read-modify-write) and initSections (read-only).
    "  function readAdvancedSectionState() {",
    "    const stored = safeStorageGet('prismcast-advanced-sections');",
    "    if(!stored) return {};",
    "    try { return JSON.parse(stored); }",
    "    catch(e) { console.warn('Advanced section state failed to parse.', e); return {}; }",
    "  }",

    "  window.toggleSection = (sectionId) => {",
    "    const section = document.querySelector('.advanced-section[data-section=\"' + sectionId + '\"]');",
    "    if(!section) return;",
    "    const header = section.querySelector('.section-header');",
    "    const content = section.querySelector('.section-content');",
    "    if(!header || !content) return;",
    "    const isExpanded = content.classList.contains('expanded');",
    "    if(isExpanded) {",
    "      content.classList.remove('expanded');",
    "      header.classList.remove('expanded');",
    "    } else {",
    "      content.classList.add('expanded');",
    "      header.classList.add('expanded');",
    "    }",
    "    const expanded = readAdvancedSectionState();",
    "    expanded[sectionId] = !isExpanded;",
    "    safeStorageSet('prismcast-advanced-sections', JSON.stringify(expanded));",
    "  };",

    // Initialize section expansion state from localStorage on page load.
    "  function initSections() {",
    "    for(const [ sectionId, isExpanded ] of Object.entries(readAdvancedSectionState())) {",
    "      if(!isExpanded) continue;",
    "      const section = document.querySelector('.advanced-section[data-section=\"' + sectionId + '\"]');",
    "      if(!section) continue;",
    "      const header = section.querySelector('.section-header');",
    "      const content = section.querySelector('.section-content');",
    "      if(header && content) {",
    "        header.classList.add('expanded');",
    "        content.classList.add('expanded');",
    "      }",
    "    }",
    "  }",
    "  initSections();",

    // Reset all settings to defaults (client-side only).
    "  window.resetAllToDefaults = () => {",
    "    if(!confirm('Reset ALL settings to defaults? Click ' + (isServiceMode ? 'Save & Restart' : 'Save Settings') + ' after to apply.')) return;",
    "    const form = document.getElementById('settings-form');",
    "    if(!form) return;",
    "    const inputs = form.querySelectorAll('input[data-default], select[data-default]');",
    "    for(const input of inputs) {",
    "      if(!input.disabled) {",
    "        setInputValue(input, input.getAttribute('data-default'));",
    "        updateModifiedIndicator(input);",
    "      }",
    "    }",
    "    const cbInputs = form.querySelectorAll('input[type=\"checkbox\"][data-default]');",
    "    for(const cbInput of cbInputs) {",
    "      if(!cbInput.disabled) {",
    "        updateDependentFields(cbInput.id);",
    "      }",
    "    }",
    "    showToast('All settings reset to defaults. Click ' + (isServiceMode ? 'Save & Restart' : 'Save Settings') + ' to apply changes.', 'info');",
    "  };",

    // Submit settings form via AJAX.
    "  window.submitSettingsForm = async (event) => {",
    "    event.preventDefault();",
    "    clearFieldErrors();",
    "    const form = document.getElementById('settings-form');",
    "    const saveBtn = document.getElementById('save-btn');",
    "    if(!form) return false;",
    "    const formData = new FormData(form);",
    "    const config = {};",
    "    for(const pair of formData.entries()) {",
    "      const path = pair[0];",
    "      const value = pair[1];",
    "      const parts = path.split('.');",
    "      let obj = config;",
    "      for(let i = 0; i < (parts.length - 1); i++) {",
    "        if(!obj[parts[i]]) obj[parts[i]] = {};",
    "        obj = obj[parts[i]];",
    "      }",
    "      obj[parts.at(-1)] = value;",
    "    }",
    "    if(saveBtn) saveBtn.classList.add('loading');",
    "    try {",
    "      const res = await fetch('/config', {",
    "        body: JSON.stringify(config),",
    "        headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const data = await res.json();",
    "      if(saveBtn) saveBtn.classList.remove('loading');",
    "      if(res.ok && data.success) {",
    "        if(data.willRestart) {",
    "          if(data.deferred) {",
    "            showPendingRestartDialog(data.activeStreams);",
    "          } else {",
    "            waitForServerRestart();",
    "          }",
    "        } else {",
    "          showToast(data.message || 'Configuration saved.', 'info');",
    "        }",
    "      } else if(data.errors) {",
    "        displayFieldErrors(data.errors);",
    "        showToast('Please correct the errors below.', 'error');",
    "      } else {",
    "        showToast(extractErrorMessage(data, 'Failed to save configuration.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      if(saveBtn) saveBtn.classList.remove('loading');",
    "      showToast('Failed to save configuration: ' + err.message, 'error');",
    "    }",
    "    return false;",
    "  };",

    // Export configuration as JSON download.
    "  window.exportConfig = async () => {",
    "    try {",
    "      const res = await fetch('/config/export');",
    "      const blob = await res.blob();",
    "      const url = window.URL.createObjectURL(blob);",
    "      const a = document.createElement('a');",
    "      a.href = url;",
    "      a.download = 'prismcast-config.json';",
    "      document.body.appendChild(a);",
    "      a.click();",
    "      document.body.removeChild(a);",
    "      window.URL.revokeObjectURL(url);",
    "    } catch(err) {",
    "      showToast('Failed to export configuration: ' + err.message, 'error');",
    "    }",
    "  };",

    // Import configuration from file.
    "  window.importConfig = (fileInput) => {",
    "    const file = fileInput.files[0];",
    "    if(!file) return;",
    "    const reader = new FileReader();",
    "    reader.onload = async (e) => {",
    "      try {",
    "        const config = JSON.parse(e.target.result);",
    "        if(confirm('Import this configuration? The server may restart to apply changes.')) {",
    "          const res = await fetch('/config/import', {",
    "            body: JSON.stringify(config),",
    "            headers: { 'Content-Type': 'application/json' },",
    "            method: 'POST'",
    "          });",
    "          const data = await res.json();",
    "          if(res.ok && data.success) {",
    "            showToast(data.message || 'Configuration imported.', 'success');",
    "            if(data.willRestart) {",
    "              if(data.deferred) {",
    "                showPendingRestartDialog(data.activeStreams);",
    "              } else {",
    "                waitForServerRestart();",
    "              }",
    "            }",
    "          } else {",
    "            throw new Error(extractErrorMessage(data, 'Import failed'));",
    "          }",
    "        }",
    "      } catch(err) {",
    "        showToast('Failed to import configuration: ' + err.message, 'error');",
    "      }",
    "      fileInput.value = '';",
    "    };",
    "    reader.readAsText(file);",
    "  };",

    // Export channels as JSON download.
    "  window.exportChannels = async () => {",
    "    try {",
    "      const res = await fetch('/config/channels/export');",
    "      const blob = await res.blob();",
    "      const url = window.URL.createObjectURL(blob);",
    "      const a = document.createElement('a');",
    "      a.href = url;",
    "      a.download = 'prismcast-channels.json';",
    "      document.body.appendChild(a);",
    "      a.click();",
    "      document.body.removeChild(a);",
    "      window.URL.revokeObjectURL(url);",
    "    } catch(err) {",
    "      showToast('Failed to export channels: ' + err.message, 'error');",
    "    }",
    "  };",

    // Import channels from file.
    "  window.importChannels = (fileInput) => {",
    "    const file = fileInput.files[0];",
    "    if(!file) return;",
    "    const reader = new FileReader();",
    "    reader.onload = async (e) => {",
    "      try {",
    "        const channels = JSON.parse(e.target.result);",
    "        if(confirm('Import these channels? This will replace all existing user channels.')) {",
    "          const res = await fetch('/config/channels/import', {",
    "            body: JSON.stringify(channels),",
    "            headers: { 'Content-Type': 'application/json' },",
    "            method: 'POST'",
    "          });",
    "          const data = await res.json();",
    "          if(data.success) {",
    "            showToast((data.message || 'Channels imported successfully.') + PLAYLIST_HINT, 'success');",
    "            if(data.patch) { channelTable.applyPatch(data.patch); }",
    "          } else {",
    "            showToast('Failed to import channels: ' + extractErrorMessage(data, 'Unknown error.'), 'error');",
    "          }",
    "        }",
    "      } catch(err) {",
    "        showToast('Failed to import channels: ' + err.message, 'error');",
    "      }",
    "      fileInput.value = '';",
    "    };",
    "    reader.readAsText(file);",
    "  };",

    // Import channels from M3U playlist file.
    "  window.importM3U = (fileInput) => {",
    "    const file = fileInput.files[0];",
    "    if(!file) return;",
    "    const replaceCheckbox = document.getElementById('m3u-replace-duplicates');",
    "    const conflictMode = (replaceCheckbox && replaceCheckbox.checked) ? 'replace' : 'skip';",
    "    const reader = new FileReader();",
    "    reader.onload = async (e) => {",
    "      try {",
    "        const res = await fetch('/config/channels/import-m3u', {",
    "          body: JSON.stringify({ content: e.target.result, conflictMode: conflictMode }),",
    "          headers: { 'Content-Type': 'application/json' },",
    "          method: 'POST'",
    "        });",
    "        const data = await res.json();",
    "        if(data.success) {",
    "          let msg = 'M3U Import Complete\\n\\n';",
    "          msg += '\\u2713 ' + data.imported + ' channel(s) imported\\n';",
    "          if(data.replaced > 0) msg += '\\u21BB ' + data.replaced + ' channel(s) replaced\\n';",
    "          if(data.skipped > 0) msg += '\\u25CB ' + data.skipped + ' duplicate(s) skipped\\n';",
    "          if(data.errors && (data.errors.length > 0)) {",
    "            msg += '\\n! ' + data.errors.length + ' error(s):\\n';",
    "            const limit = Math.min(data.errors.length, 5);",
    "            for(let i = 0; i < limit; i++) {",
    "              msg += '  - ' + data.errors[i] + '\\n';",
    "            }",
    "            if(data.errors.length > 5) msg += '  ... and ' + (data.errors.length - 5) + ' more\\n';",
    "          }",
    "          if(data.patch) { channelTable.applyPatch(data.patch); }",
    "          showToast(msg + (((data.imported > 0) || (data.replaced > 0)) ? PLAYLIST_HINT : ''), 'success');",
    "        } else {",
    "          showToast('M3U import failed: ' + extractErrorMessage(data, 'Unknown error'), 'error');",
    "        }",
    "      } catch(err) {",
    "        console.error('M3U channel import failed.', err);",
    "        showToast('Failed to import M3U: ' + err.message, 'error');",
    "      }",
    "      fileInput.value = '';",
    "    };",
    "    reader.readAsText(file);",
    "  };",

    // Client-side validation for numeric inputs.
    "  function validateInput(input) {",
    "    const min = input.min !== '' ? Number(input.min) : null;",
    "    const max = input.max !== '' ? Number(input.max) : null;",
    "    const value = Number(input.value);",
    "    let isValid = true;",
    "    if(input.type === 'number') {",
    "      if(isNaN(value)) { isValid = false; }",
    "      else if((min !== null) && (value < min)) { isValid = false; }",
    "      else if((max !== null) && (value > max)) { isValid = false; }",
    "    }",
    "    if(isValid) {",
    "      input.classList.remove('error');",
    "    } else {",
    "      input.classList.add('error');",
    "    }",
    "    return isValid;",
    "  }",

    // Subtab switching via the shared factory. The onSwitch callback handles the config-specific behavior of hiding settings buttons on the backup subtab.
    "  const switchSubtab = createSubtabSwitcher({",
    "    btnSelector: '.subtab-btn',",
    "    dataAttr: 'data-subtab',",
    "    hashFn: (s) => '#config/' + s,",
    "    onSwitch: (subtab) => {",
    "      const settingsButtons = document.getElementById('settings-buttons');",
    "      if(settingsButtons) settingsButtons.style.display = (subtab === 'backup') ? 'none' : 'flex';",
    "    },",
    "    panelPrefix: 'subtab-',",
    "    panelSelector: '.subtab-panel',",
    "    storageKey: 'prismcast-config-subtab'",
    "  });",
    "  window.switchConfigSubtab = switchSubtab;",

    // Channel edit form show/hide functions.
    "  window.showEditForm = (key) => {",
    "    const displayRow = document.getElementById('display-row-' + key);",
    "    const editRow = document.getElementById('edit-row-' + key);",
    "    if(displayRow) displayRow.style.display = 'none';",
    "    if(editRow) {",
    "      editRow.style.display = '';",
    "      updateSelectorSuggestions('edit-url-' + key, 'edit-' + key + '-selectorList');",
    "      const urlInput = document.getElementById('edit-url-' + key);",
    "      if(urlInput && !urlInput.dataset.selectorBound) {",
    "        urlInput.addEventListener('input', () => { updateSelectorSuggestions('edit-url-' + key, 'edit-' + key + '-selectorList'); });",
    "        urlInput.dataset.selectorBound = 'true';",
    "      }",
    "    }",
    "  };",
    "  window.hideEditForm = (key) => {",
    "    const displayRow = document.getElementById('display-row-' + key);",
    "    const editRow = document.getElementById('edit-row-' + key);",
    "    if(displayRow) displayRow.style.display = '';",
    "    if(editRow) editRow.style.display = 'none';",
    "  };",

    // Reset a single channel edit form field to its predefined default. Reads the data-default attribute, sets the value, removes the modified treatment
    // (border accent, dot, reset button), and dispatches events so dependent handlers (e.g., tag checkbox sync) update. Same pattern as the settings form's
    // resetSetting() but for channel fields within the edit form.
    "  window.resetChannelField = (inputId) => {",
    "    const input = document.getElementById(inputId);",
    "    if(!input) return;",
    "    const defaultVal = input.getAttribute('data-default');",
    "    if(defaultVal === null) return;",
    "    setInputValue(input, defaultVal);",
    "    const row = input.closest('.form-row');",
    "    if(row) {",
    "      row.classList.remove('modified');",
    "      const dot = row.querySelector('.modified-dot');",
    "      if(dot) dot.remove();",
    "      const btn = row.querySelector('.btn-reset');",
    "      if(btn) btn.remove();",
    "    }",
    "    input.dispatchEvent(new Event('input', { bubbles: true }));",
    "    input.dispatchEvent(new Event('change', { bubbles: true }));",
    "  };",

    // Select a service pill in the add form. Clicking an inactive pill highlights it, fills the URL field, sets profile to autodetect (disabled), and expands
    // the advanced section (channel selector is essential for service channels). Clicking the active pill deselects it, clears the URL, and re-enables the
    // profile dropdown for manual entry mode.
    "  window.selectServicePill = (btn) => {",
    "    const wasActive = btn.classList.contains('active');",
    "    const pills = btn.parentElement.querySelectorAll('.provider-pill');",
    "    for(const pill of pills) pill.classList.remove('active');",
    "    if(!wasActive) btn.classList.add('active');",
    "    const urlInput = document.getElementById('add-url');",
    "    if(urlInput) {",
    "      urlInput.value = wasActive ? '' : (btn.getAttribute('data-url') || '');",
    "      urlInput.dispatchEvent(new Event('input', { bubbles: true }));",
    "    }",
    "    const profileSelect = document.getElementById('add-profile');",
    "    if(profileSelect) {",
    "      if(!wasActive) { profileSelect.value = ''; profileSelect.disabled = true; }",
    "      else { profileSelect.disabled = false; }",
    "    }",
    "    if(!wasActive) {",
    "      const advanced = document.getElementById('add-advanced');",
    "      const toggle = advanced ? advanced.previousElementSibling : null;",
    "      if(advanced && !advanced.classList.contains('show')) {",
    "        advanced.classList.add('show');",
    "        if(toggle) toggle.textContent = 'Hide Advanced Options';",
    "      }",
    "    }",
    "  };",

    // Hide the add form and reset all fields and service pill selection.
    "  window.hideAddForm = () => {",
    "    const addForm = document.getElementById('add-channel-form');",
    "    if(addForm) addForm.style.display = 'none';",
    "    if(addForm) {",
    "      addForm.querySelector('form').reset();",
    "      const pills = addForm.querySelectorAll('.provider-pill');",
    "      for(const pill of pills) pill.classList.remove('active');",
    "      const profileSelect = addForm.querySelector('#add-profile');",
    "      if(profileSelect) profileSelect.disabled = false;",
    "    }",
    "  };",

    // Advanced fields toggle for channel forms.
    "  window.toggleAdvanced = (prefix) => {",
    "    const fields = document.getElementById(prefix + '-advanced');",
    "    const toggle = document.getElementById(prefix + '-toggle');",
    "    if(fields && toggle) {",
    "      if(fields.classList.contains('show')) {",
    "        fields.classList.remove('show');",
    "        toggle.textContent = '\\u25B6 Show Advanced Options';",
    "      } else {",
    "        fields.classList.add('show');",
    "        toggle.textContent = '\\u25BC Hide Advanced Options';",
    "      }",
    "    }",
    "  };",

    // Profile reference toggle.
    "  window.toggleProfileReference = () => {",
    "    const ref = document.getElementById('profile-reference');",
    "    if(ref) {",
    "      ref.style.display = ref.style.display === 'none' ? 'block' : 'none';",
    "    }",
    "  };",

    // Inline cell editing for channel number and station ID. Clicking an editable cell replaces its content with a text input. Enter or blur PATCHes the channel
    // record at /config/channels/:key with a typed partial update. Escape cancels and restores the original value. The cell's data attributes carry the field
    // name, channel key, and current value so the handler is generic across both fields.
    "  window.startInlineEdit = (td) => {",
    "    if(td.querySelector('input.inline-edit')) return;",
    "    const field = td.getAttribute('data-field');",
    "    const key = td.getAttribute('data-key');",
    "    const value = td.getAttribute('data-value') || '';",
    "    const original = td.innerHTML;",
    "    const input = document.createElement('input');",
    "    input.type = (field === 'channelNumber') ? 'number' : 'text';",
    "    input.className = 'inline-edit';",
    "    input.value = value;",
    "    td.innerHTML = '';",
    "    td.appendChild(input);",
    "    input.focus();",
    "    input.select();",
    "    let saving = false;",
    "    async function save() {",
    "      if(saving) return;",
    "      saving = true;",
    "      const newValue = input.value.trim();",
    "      if(newValue === value) { cancel(); return; }",
    // Build a typed partial-update body. channelNumber is parsed as an integer (null clears). stationId uses "" for empty converted to null.
    "      const body = {};",
    "      if(field === 'channelNumber') body.channelNumber = newValue ? parseInt(newValue, 10) : null;",
    "      else if(field === 'stationId') body.stationId = newValue || null;",
    "      else body[field] = newValue;",
    "      try {",
    "        const res = await fetch('/config/channels/' + encodeURIComponent(key), {",
    "          body: JSON.stringify(body),",
    "          headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },",
    "          method: 'PATCH'",
    "        });",
    "        const d = await res.json();",
    "        if(res.ok && d.success) {",
    "          if(d.patch) { channelTable.applyPatch(d.patch); }",
    "        } else {",
    "          td.innerHTML = original;",
    "          showToast(extractErrorMessage(d, 'Failed to save.'), 'error');",
    "        }",
    "      } catch(err) {",
    "        console.error('Channel inline edit failed.', err);",
    "        td.innerHTML = original;",
    "        showToast('Failed to save: ' + err.message, 'error');",
    "      }",
    "    }",
    "    function cancel() { td.innerHTML = original; }",
    "    input.addEventListener('keydown', (e) => {",
    "      if(e.key === 'Enter') { e.preventDefault(); save(); }",
    "      else if(e.key === 'Escape') { cancel(); }",
    "    });",
    "    input.addEventListener('blur', () => { if(!saving) save(); });",
    "  };",

    // Toggle HDHR lineup inclusion for a channel via inline checkbox. Uses the inline-edit endpoint with hdhrEnabled field.
    "  window.toggleHdhr = async (checkbox) => {",
    "    const key = checkbox.getAttribute('data-key');",
    "    try {",
    "      const res = await fetch('/config/channels/' + encodeURIComponent(key), {",
    "        body: JSON.stringify({ hdhrEnabled: checkbox.checked }),",
    "        headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },",
    "        method: 'PATCH'",
    "      });",
    "      const d = await res.json();",
    "      if(res.ok && d.success) {",
    "        if(d.patch) { channelTable.applyPatch(d.patch); }",
    "      } else {",
    "        checkbox.checked = !checkbox.checked;",
    "        showToast(extractErrorMessage(d, 'Failed to update HDHR setting.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      checkbox.checked = !checkbox.checked;",
    "      showToast('Failed to update HDHR setting: ' + err.message, 'error');",
    "    }",
    "  };",

    // Submit channel form via AJAX (add or edit).
    "  window.submitChannelForm = async (event, action) => {",
    "    event.preventDefault();",
    "    const form = event.target;",
    "    const formData = new FormData(form);",
    "    const data = {};",
    "    for(const pair of formData.entries()) { data[pair[0]] = pair[1]; }",
    // RESTful split: new channels go to POST /config/channels; edits go to PUT /config/channels/:key.
    "    const url = (action === 'add') ? '/config/channels' : ('/config/channels/' + encodeURIComponent(data.key));",
    "    const method = (action === 'add') ? 'POST' : 'PUT';",
    "    try {",
    "      const res = await fetch(url, {",
    "        body: JSON.stringify(data),",
    "        headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },",
    "        method: method",
    "      });",
    "      const d = await res.json();",
    "      if(res.ok && d.success) {",
    "        showToast(d.message, 'success');",
    "        if(d.patch) { channelTable.applyPatch(d.patch); }",
    "        if(action === 'add') {",
    "          hideAddForm();",
    "          if(d.serviceWarning) { showServiceFilterWarning(d.serviceWarning); }",
    "        } else {",
    "          hideEditForm(d.key);",
    "        }",
    "      } else {",
    "        showToast(extractErrorMessage(d, 'Failed to save channel.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Channel save request failed.', err);",
    "      showToast('Failed to save channel: ' + err.message, 'error');",
    "    }",
    "    return false;",
    "  };",

    // Delete channel via AJAX.
    "  window.deleteChannel = async (key) => {",
    "    if(!confirm('Delete channel ' + key + '?')) return;",
    "    try {",
    "      const res = await fetch('/config/channels/' + encodeURIComponent(key), {",
    "        headers: { 'Accept': 'application/json' },",
    "        method: 'DELETE'",
    "      });",
    "      const d = await res.json();",
    "      if(res.ok && d.success) {",
    "        showToast(d.message, 'success');",
    "        if(d.patch) { channelTable.applyPatch(d.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(d, 'Failed to delete channel.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Channel delete request failed.', err);",
    "      showToast('Failed to delete channel: ' + err.message, 'error');",
    "    }",
    "  };",

    // Toggle a single predefined channel's enabled/disabled state.
    "  window.togglePredefinedChannel = async (key, enable) => {",
    "    try {",
    "      const res = await fetch('/config/channels/toggle-predefined', {",
    "        body: JSON.stringify({ key: key, enabled: enable }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        showToast('Channel ' + key + ' ' + (enable ? 'enabled' : 'disabled') + '.' + PLAYLIST_HINT, 'success');",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to toggle channel.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Channel toggle request failed.', err);",
    "      showToast('Failed to toggle channel: ' + err.message, 'error');",
    "    }",
    "  };",

    // Update a channel row's service selection in-place. Syncs the HTML selected attribute so channelTable.filter() restore logic works correctly. We iterate
    // _allOptions (if present) rather than querySelectorAll because filtered-out options are removed from the DOM but still tracked in the array.
    "  function updateChannelServiceUI(channelKey, variant) {",
    "    const row = document.getElementById('display-row-' + channelKey);",
    "    if(!row) return;",
    "    const sel = row.querySelector('.provider-select');",
    "    if(!sel) return;",
    "    sel.value = variant;",
    "    const allOpts = sel._allOptions || [...sel.querySelectorAll('option')];",
    "    for(const opt of allOpts) {",
    "      if(opt.value === variant) { opt.setAttribute('selected', ''); }",
    "      else { opt.removeAttribute('selected'); }",
    "    }",
    "  }",

    // Update service selection for a multi-service channel.
    "  window.updateServiceSelection = async (selectElement) => {",
    "    const channelKey = selectElement.getAttribute('data-channel');",
    "    const serviceKey = selectElement.value;",
    "    try {",
    "      const res = await fetch('/config/channels/' + encodeURIComponent(channelKey) + '/service', {",
    "        body: JSON.stringify({ service: serviceKey }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'PUT'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        showToast('Service updated. New streams will use the selected service.', 'success');",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to update service.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Service selection update failed.', err);",
    "      showToast('Failed to update service: ' + err.message, 'error');",
    "    }",
    "  };",

    // Bulk toggle predefined channels by scope (all, pacific, east).
    "  window.bulkTogglePredefined = async (enable, scope) => {",
    "    try {",
    "      const res = await fetch('/config/channels/bulk-toggle-predefined', {",
    "        body: JSON.stringify({ enabled: enable, scope: scope }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        const labels = { all: 'All predefined', pacific: 'Pacific predefined', east: 'East predefined' };",
    "        showToast((labels[scope] || 'Predefined') + ' channels ' + (enable ? 'enabled' : 'disabled') + '.' + PLAYLIST_HINT, 'success');",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to toggle channels.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Bulk channel toggle failed.', err);",
    "      showToast('Failed to toggle channels: ' + err.message, 'error');",
    "    }",
    "  };",

    // Auto-number visible channels sequentially based on the current sort order. Reads the starting number from the input in the Quick Actions dropdown. When
    // the input is empty, clears all channel numbers from visible channels instead of assigning them.
    "  window.autoNumberChannels = async () => {",
    "    const startInput = document.getElementById('auto-number-start');",
    "    const raw = startInput ? startInput.value.trim() : '1';",
    "    const clear = (raw === '');",
    "    let start = clear ? 0 : parseInt(raw, 10);",
    "    if(!clear && (isNaN(start) || (start < 1))) start = 1;",
    "    const table = document.querySelector('.channel-table');",
    "    const sortField = table ? (table.getAttribute('data-sort-field') || 'name') : 'name';",
    "    const sortDir = table ? (table.getAttribute('data-sort-dir') || 'asc') : 'asc';",
    "    const msg = clear ? 'Clear channel numbers from all visible channels?' " +
    ": 'Assign channel numbers starting from ' + start + ' to all visible channels in the current sort order? This will overwrite existing numbers.';",
    "    if(!confirm(msg)) return;",
    "    try {",
    "      const res = await fetch('/config/channels/auto-number', {",
    "        body: JSON.stringify({ start: start, sortField: sortField, sortDirection: sortDir }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        showToast(result.message || 'Channels numbered.', 'success');",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to auto-number channels.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Channel auto-numbering failed.', err);",
    "      showToast('Failed to auto-number channels: ' + err.message, 'error');",
    "    }",
    "  };",

    // Bulk toggle HDHR lineup inclusion for all visible channels. The tri-state checkbox calls this on click: from checked (all enabled) it disables all; from
    // unchecked or indeterminate it enables all.
    "  window.bulkToggleHdhr = async () => {",
    "    const toggle = document.getElementById('hdhr-bulk-toggle');",
    "    if(!toggle) return;",
    "    const enable = !toggle.checked;",
    "    const msg = enable ? 'Include all visible channels in the HDHomeRun/Plex lineup?' : 'Exclude all visible channels from the HDHomeRun/Plex lineup?';",
    "    if(!confirm(msg)) return;",
    "    try {",
    "      const res = await fetch('/config/channels/hdhr-bulk', {",
    "        body: JSON.stringify({ enable: enable }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        showToast(result.message || 'HDHR settings updated.', 'success');",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to update HDHR settings.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('HDHR bulk toggle failed.', err);",
    "      showToast('Failed to update HDHR settings: ' + err.message, 'error');",
    "    }",
    "  };",

    // Bulk add or remove a tag on all visible channels. The add parameter controls the direction: true adds the tag, false removes it. The tristate checkbox in
    // Quick Actions calls this on click — from checked (all have tag) it removes; from unchecked or indeterminate it adds. Uses applyTagResponse (defined in
    // channels.ts, exposed on window) to update the tag manager modal, filter dropdown, and channel table in one call.
    "  window.bulkToggleTag = async (tag, add) => {",
    "    try {",
    "      const res = await fetch('/config/channels/bulk-tags', {",
    "        body: JSON.stringify({ action: add ? 'add' : 'remove', tag: tag }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        if(window.applyTagResponse) { window.applyTagResponse(result, result.message || 'Tags updated.'); }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to update tags.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      console.error('Bulk tag update failed.', err);",
    "      showToast('Failed to update tags: ' + err.message, 'error');",
    "    }",
    "  };",

    // Inline tag edit portal — uses toggleDropdown with lifecycle hooks for batch-save behavior. The before-close hook saves pending changes whenever the
    // dropdown closes (click-outside, scroll, resize, or next toggle). The onOpen hook populates checkbox state from the cell's data-tags attribute.
    "  let activeTagDropdown = null;",
    "  let tagPortal = null;",

    "  function getTagPortal() {",
    "    if(!tagPortal) { tagPortal = document.getElementById('inline-tag-portal'); }",
    "    return tagPortal;",
    "  }",

    "  async function saveTagDropdownIfChanged() {",
    "    if(!activeTagDropdown) return;",
    "    const portal = getTagPortal();",
    "    if(!portal) return;",
    "    const original = activeTagDropdown.original;",
    "    const key = activeTagDropdown.key;",
    "    const checkboxes = portal.querySelectorAll('.inline-tag-checkbox');",
    "    const tags = [];",
    "    for(const checkbox of checkboxes) {",
    "      if(checkbox.checked) tags.push(checkbox.getAttribute('data-tag'));",
    "    }",
    "    const newValue = tags.toSorted().join(',');",
    "    activeTagDropdown = null;",
    "    if(newValue === original) return;",
    "    try {",
    "      const res = await fetch('/config/channels/' + encodeURIComponent(key), {",
    "        body: JSON.stringify({ tags: tags }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'PATCH'",
    "      });",
    "      const d = await res.json();",
    "      if(d.success && d.patch) { channelTable.applyPatch(d.patch); }",
    "      else if(!d.success) { showToast(extractErrorMessage(d, 'Failed to update tags.'), 'error'); }",
    "    } catch(err) {",
    "      console.error('Tag edit failed to persist.', err);",
    "      showToast('Failed to update tags: ' + err.message, 'error');",
    "    }",
    "  }",

    // Register the batch-save hook so all close paths (click-outside, scroll, resize, next toggle) trigger save.
    "  dropdowns.addHook(saveTagDropdownIfChanged);",

    "  window.toggleInlineTagDropdown = (td) => {",
    "    const portal = getTagPortal();",
    "    if(!portal) return;",
    "    const isOpen = activeTagDropdown && (activeTagDropdown.td === td);",
    "    dropdowns.close();",
    "    if(isOpen) return;",
    // Populate checkbox state from the cell's data-tags attribute, then toggle the dropdown with the shared portal positioning.
    "    const currentTags = (td.getAttribute('data-tags') || '').split(',').filter((t) => t.length > 0);",
    "    const tagSet = {};",
    "    for(const currentTag of currentTags) tagSet[currentTag] = true;",
    "    const checkboxes = portal.querySelectorAll('.inline-tag-checkbox');",
    "    for(const checkbox of checkboxes) {",
    "      checkbox.checked = !!tagSet[checkbox.getAttribute('data-tag')];",
    "    }",
    "    toggleDropdown(td, { menu: portal });",
    "    activeTagDropdown = { key: td.getAttribute('data-key'), original: currentTags.toSorted().join(','), td };",
    "  };",

    // Collect checked tag checkboxes into the hidden tags input for form submission. Called when any tag checkbox changes in the channel edit form.
    "  window.updateTagsHidden = (formRow) => {",
    "    const checkboxes = formRow.querySelectorAll('.tag-checkbox:checked');",
    "    const tags = [];",
    "    for(const checkbox of checkboxes) tags.push(checkbox.getAttribute('data-tag'));",
    "    const hidden = formRow.querySelector('input[type=\"hidden\"][name=\"tags\"]');",
    "    if(hidden) hidden.value = tags.toSorted().join(', ');",
    "  };",

    // Revert a channel override back to predefined defaults.
    "  window.revertChannel = async (key) => {",
    "    if(!confirm('Revert channel ' + key + ' to predefined defaults?')) return;",
    "    try {",
    "      const res = await fetch('/config/channels/' + encodeURIComponent(key) + '/revert', {",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const d = await res.json();",
    "      if(res.ok && d.success) {",
    "        showToast(d.message, 'success');",
    "        if(d.patch) { channelTable.applyPatch(d.patch); }",
    "      } else {",
    "        showToast(extractErrorMessage(d, 'Failed to revert channel.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to revert channel: ' + err.message, 'error');",
    "    }",
    "  };",

    // Save the service filter to the server and update the UI on success.
    "  async function saveServiceFilter(enabledTags) {",
    "    try {",
    "      const r = await fetch('/config/service-filter', {",
    "        body: JSON.stringify({ enabledServices: enabledTags }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await r.json();",
    "      if(result.success) {",
    "        updateServiceChips(enabledTags);",
    "        channelTable.filter(enabledTags);",
    "        updateBulkAssignOptions(enabledTags);",
    "        updateServiceFilterButton(enabledTags);",
    "        if(result.patch) { channelTable.applyPatch(result.patch); }",
    "        showToast('Service filter updated.' + PLAYLIST_HINT, 'success');",
    "      }",
    "    } catch(err) {",
    "      console.error('Service filter update failed.', err);",
    "      showToast('Failed to update filter: ' + err.message, 'error');",
    "    }",
    "  };",

    // Show a toast warning when a newly added channel's service isn't in the active filter. Offers a one-click action to enable the service tag.
    "  function showServiceFilterWarning(warning) {",
    "    showToast(warning.serviceLabel + ' is not in your active service filter. Channels won\\'t appear in the playlist until enabled.', 'warning', 10000,",
    "      { label: 'Enable ' + warning.serviceLabel, onclick: () => { enableServiceInFilter(warning.serviceTag); } });",
    "  }",

    // Enable a service tag in the filter by adding it to the current set and saving. Called by the service filter warning toast action button.
    "  async function enableServiceInFilter(tag) {",
    "    const chips = document.querySelectorAll('#provider-chips .provider-chip[data-tag]');",
    "    const enabledTags = [];",
    "    for(const chip of chips) { enabledTags.push(chip.getAttribute('data-tag')); }",
    "    if(!enabledTags.includes(tag)) { enabledTags.push(tag); }",
    "    await saveServiceFilter(enabledTags);",
    "  }",

    // Service filter: toggle a service tag on/off. The checkbox change has already been applied to the DOM, so getEnabledFilterTags() reads the new state directly.
    "  window.toggleServiceTag = (checkbox) => {",
    "    saveServiceFilter(channelTable.getEnabledFilterTags());",
    "  };",

    // Remove a service chip (uncheck the tag and update). Orphaned tags (no checkbox in the dropdown) are removed by rebuilding the list from the remaining chips.
    "  window.removeServiceChip = (tag) => {",
    "    const menu = document.querySelector('.provider-dropdown-menu');",
    "    if(!menu) return;",
    "    const cb = menu.querySelector('input[data-tag=\"' + tag + '\"]');",
    "    if(cb) { cb.checked = false; toggleServiceTag(cb); return; }",

    // No checkbox exists for this tag — it is an orphaned entry with no corresponding service. Build the enabled list from the remaining chips and POST directly.
    "    const chips = document.querySelectorAll('#provider-chips .provider-chip[data-tag]');",
    "    const enabledTags = [];",
    "    for(const chip of chips) {",
    "      const ct = chip.getAttribute('data-tag');",
    "      if(ct && (ct !== tag)) enabledTags.push(ct);",
    "    }",
    "    saveServiceFilter(enabledTags);",
    "  };",

    // Update the service filter button text. The filter icon SVG is inlined here because this runs client-side where the server's icon module is not available.
    "  const filterIcon = '<svg width=\"14\" height=\"14\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" " +
      "stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1 2h14l-5 6v5l-4 2V8z\"/></svg>';",
    "  function updateServiceFilterButton(enabledTags) {",
    "    const btn = document.getElementById('provider-filter-btn');",
    "    if(!btn) return;",
    "    const label = (enabledTags.length > 0) ? 'Filtered' : 'All Services';",
    "    btn.innerHTML = filterIcon + ' ' + label + ' &#9662;';",
    "  };",

    // Rebuild the service chips from the enabled tags.
    "  function updateServiceChips(enabledTags) {",
    "    const container = document.getElementById('provider-chips');",
    "    if(!container) return;",
    "    container.innerHTML = '';",
    "    if(enabledTags.length === 0) return;",
    "    const menu = document.querySelector('.provider-dropdown-menu');",
    "    for(const tag of enabledTags) {",
    "      if(tag === 'direct') continue;",
    "      let label = tag;",
    "      let chipDomain = '';",
    "      let chipIconUrl = '';",
    "      if(menu) {",
    "        const cb = menu.querySelector('input[data-tag=\"' + tag + '\"]');",
    "        if(cb && cb.parentElement) {",
    "          label = cb.parentElement.textContent.trim();",
    "          const pd = cb.parentElement.querySelector('.provider-display');",
    "          if(pd) {",
    "            chipDomain = pd.getAttribute('data-domain') || '';",
    "            chipIconUrl = pd.getAttribute('data-icon-url') || '';",
    "          }",
    "        }",
    "      }",
    "      const chip = document.createElement('span');",
    "      chip.className = 'provider-chip';",
    "      chip.setAttribute('data-tag', tag);",
    "      const domainAttr = chipDomain ? ' data-domain=\"' + chipDomain + '\"' : '';",
    "      const iconAttr = chipIconUrl ? ' data-icon-url=\"' + chipIconUrl + '\"' : '';",
    "      chip.innerHTML = '<span class=\"provider-display\"' + domainAttr + iconAttr + ' data-sm>' + label + '</span>' +",
    "        '<button type=\"button\" class=\"chip-close\" aria-label=\"Remove ' + label +",
    "        '\" onclick=\"removeServiceChip(\\'' + tag + '\\')\">\\u00d7</button>';",
    "      container.appendChild(chip);",
    "    }",
    "    processServiceDisplays();",
    "  };",

    // Update bulk assign options in the Quick Actions select to only show enabled services. Toggles the hidden attribute on option elements based on the filter.
    "  function updateBulkAssignOptions(enabledTags) {",
    "    const select = document.getElementById('bulk-assign-select');",
    "    if(!select) return;",
    "    const options = select.querySelectorAll('option[data-provider-tag]');",
    "    for(const option of options) {",
    "      const tag = option.getAttribute('data-provider-tag');",
    "      const show = (enabledTags.length === 0) || (tag === 'direct') || enabledTags.includes(tag);",
    "      if(show) option.removeAttribute('hidden');",
    "      else option.setAttribute('hidden', '');",
    "    }",
    "  };",

    // Bulk assign all channels to a specific service. Updates all dropdowns and profile cells in-place.
    "  window.bulkAssignService = async (serviceTag) => {",
    "    if(!serviceTag) return;",
    "    try {",
    "      const r = await fetch('/config/service-bulk-assign', {",
    "        body: JSON.stringify({ service: serviceTag }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await r.json();",
    "      if(result.success) {",
    "        const msg = result.affected + ' of ' + result.total + ' channel(s) updated.';",
    "        let undoAction = null;",
    "        if((result.affected > 0) && result.previousSelections) {",
    "          const prevSelections = result.previousSelections;",
    "          undoAction = { label: 'Undo', onclick: () => { restoreBulkServices(prevSelections); } };",
    "        }",
    "        showToast(msg, 'success', undoAction ? 10000 : undefined, undoAction);",
    "        if(result.selections) {",
    "          for(const [ key, sel ] of Object.entries(result.selections)) {",
    "            updateChannelServiceUI(key, sel.variant);",
    "          }",
    "        }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to assign.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to assign: ' + err.message, 'error');",
    "    }",
    "  };",

    // Restore previous service selections (undo bulk assign). Sends the previousSelections map to the server and updates the UI with the restored selections.
    "  async function restoreBulkServices(prevSelections) {",
    "    try {",
    "      const r = await fetch('/config/service-bulk-restore', {",
    "        body: JSON.stringify({ selections: prevSelections }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await r.json();",
    "      if(result.success) {",
    "        showToast('Bulk assign reverted.', 'success');",
    "        if(result.selections) {",
    "          for(const [ key, sel ] of Object.entries(result.selections)) {",
    "            updateChannelServiceUI(key, sel.variant);",
    "          }",
    "        }",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to revert.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to revert: ' + err.message, 'error');",
    "    }",
    "  }",


    // Close dropdowns when clicking outside. After portaling, menus live on <body> outside .dropdown containers, so we also check .dropdown-menu to prevent
    // clicks on menu items (like column picker checkboxes) from triggering close.
    "  document.addEventListener('click', (e) => {",
    "    if(!e.target.closest('.dropdown') && !e.target.closest('.dropdown-menu')) dropdowns.close();",
    "  });",

    // Copy a stream URL to the clipboard. The type parameter selects HLS or MPEG-TS format. Delegates to the shared copyToClipboard utility.
    "  window.copyStreamUrl = (type, key) => {",
    "    dropdowns.close();",
    "    const url = (type === 'hls') ? (location.origin + '/hls/' + key + '/stream.m3u8') : (location.origin + '/stream/' + key);",
    "    copyToClipboard(url, 'Stream URL copied to clipboard.');",
    "  };",

    // Toggle visibility of disabled predefined channels and persist preference.
    "  window.toggleDisabledVisibility = () => {",
    "    const table = document.querySelector('.channel-table');",
    "    const checkbox = document.getElementById('show-disabled-toggle');",
    "    if(!table || !checkbox) return;",
    "    if(checkbox.checked) {",
    "      table.classList.remove('hide-disabled');",
    "      safeStorageSet('prismcast-show-disabled-channels', 'true');",
    "    } else {",
    "      table.classList.add('hide-disabled');",
    "      safeStorageRemove('prismcast-show-disabled-channels');",
    "    }",
    "  };",

    // Toggle visibility of an optional column and persist via background POST.
    "  window.toggleColumn = (checkbox) => {",
    "    const table = document.querySelector('.channel-table');",
    "    if(!table || !checkbox) return;",
    "    const colClass = checkbox.getAttribute('data-col-class');",
    "    const hideClass = 'hide-' + colClass;",
    "    if(checkbox.checked) { table.classList.remove(hideClass); }",
    "    else { table.classList.add(hideClass); }",
    // Collect all currently checked columns from the picker menu.
    "    const menu = document.querySelector('.column-picker-menu');",
    "    const cols = [];",
    "    if(menu) {",
    "      const cbs = menu.querySelectorAll('input[type=\"checkbox\"][data-col-field]');",
    "      for(const cb of cbs) {",
    "        if(cb.checked) cols.push(cb.getAttribute('data-col-field'));",
    "      }",
    "    }",
    // Show or hide Quick Action sections gated on column visibility.
    "    const colField = checkbox.getAttribute('data-col-field');",
    "    const qaMap = { channelNumber: 'quick-action-autonumber', hdhrEnabled: 'quick-action-hdhr' };",
    "    const qaId = qaMap[colField];",
    "    if(qaId) {",
    "      const qaEl = document.getElementById(qaId);",
    "      if(qaEl) qaEl.style.display = checkbox.checked ? '' : 'none';",
    "      const divider = document.getElementById('quick-action-divider');",
    "      const anyVisible = (document.getElementById('quick-action-autonumber')?.style.display !== 'none') ||",
    "        (document.getElementById('quick-action-hdhr')?.style.display !== 'none');",
    "      if(divider) divider.style.display = anyVisible ? '' : 'none';",
    "    }",
    "    persistDisplayPrefs({ visibleColumns: cols });",
    "  };",

    // Populate channel selector datalist based on the URL field value. First populates from server-rendered data (predefined channels and cached provider
    // discovery), then asynchronously fetches from the provider discovery endpoint to pick up any channels not yet in the static data.
    "  function updateSelectorSuggestions(urlInputId, datalistId) {",
    "    const urlInput = document.getElementById(urlInputId);",
    "    const datalist = document.getElementById(datalistId);",
    "    if(!urlInput || !datalist) return;",
    "    datalist.innerHTML = '';",

    // Find or create the URL hint element. Placed after the URL input's parent form-row so it sits below the field.
    "    const hintId = urlInputId + '-url-hint';",
    "    let hintEl = document.getElementById(hintId);",
    "    if(!hintEl) {",
    "      hintEl = document.createElement('div');",
    "      hintEl.id = hintId;",
    "      hintEl.className = 'hint';",
    "      hintEl.style.marginBottom = '0';",
    "      const formRow = urlInput.closest('.form-row');",
    "      if(formRow) { formRow.parentNode.insertBefore(hintEl, formRow.nextSibling); }",
    "    }",
    "    hintEl.innerHTML = '';",
    "    hintEl.style.display = 'none';",

    "    let raw = urlInput.value;",
    "    if(raw && !raw.startsWith('http://') && !raw.startsWith('https://')) { raw = 'https://' + raw; }",
    "    const parsed = URL.parse(raw);",
    "    if(!parsed) return;",
    "    const hostname = parsed.hostname;",
    "    const alt = hostname.startsWith('www.') ? hostname.substring(4) : 'www.' + hostname;",
    // Resolve the provider hostname. Try exact match first, then www-variant, then base domain match (e.g., sling.com matches watch.sling.com).
    "    const exactMatch = (typeof channelSelectorsByDomain !== 'undefined') && channelSelectorsByDomain[hostname];",
    "    let resolvedHostname = null;",
    "    if((typeof serviceByDomain !== 'undefined') && serviceByDomain[hostname]) { resolvedHostname = hostname; }",
    "    else if((typeof serviceByDomain !== 'undefined') && serviceByDomain[alt]) { resolvedHostname = alt; }",
    "    else if(typeof serviceByDomain !== 'undefined') {",
    "      const suffix = '.' + hostname;",
    "      const domainKeys = Object.keys(serviceByDomain);",
    "      for(const domainKey of domainKeys) {",
    "        if(domainKey.endsWith(suffix)) { resolvedHostname = domainKey; break; }",
    "      }",
    "    }",
    "    const slug = resolvedHostname ? serviceByDomain[resolvedHostname] : null;",
    "    const entries = exactMatch || ((typeof channelSelectorsByDomain !== 'undefined')",
    "      ? (channelSelectorsByDomain[alt] || (resolvedHostname ? channelSelectorsByDomain[resolvedHostname] : null)) : null);",
    "    if(entries) {",
    "      for(const entry of entries) {",
    "        const opt = document.createElement('option');",
    "        opt.value = entry.value;",
    "        opt.label = entry.label;",
    "        datalist.appendChild(opt);",
    "      }",
    "    }",

    // Show a URL hint when the hostname didn't match exactly and we found a provider via fallback.
    "    if(!exactMatch && slug && (typeof serviceGuideUrl !== 'undefined') && serviceGuideUrl[slug]) {",
    "      const suggestedUrl = serviceGuideUrl[slug];",
    "      const link = document.createElement('a');",
    "      link.href = '#';",
    "      link.textContent = suggestedUrl;",
    "      link.addEventListener('click', (e) => {",
    "        e.preventDefault();",
    "        urlInput.value = suggestedUrl;",
    "        hintEl.innerHTML = '';",
    "        hintEl.style.display = 'none';",
    "        updateSelectorSuggestions(urlInputId, datalistId);",
    "      });",
    "      hintEl.appendChild(document.createTextNode('Did you mean '));",
    "      hintEl.appendChild(link);",
    "      hintEl.appendChild(document.createTextNode('?'));",
    "      hintEl.style.display = '';",
    "    }",

    "    if(!slug) return;",
    "    const snapshotUrl = urlInput.value;",
    "    (async () => {",
    "      try {",
    "        const r = await fetch('/services/' + slug + '/channels');",
    "        const channels = r.ok ? await r.json() : null;",
    "        if(!channels || (urlInput.value !== snapshotUrl)) return;",
    "        const existing = {};",
    "        const opts = datalist.querySelectorAll('option');",
    "        for(const opt of opts) { existing[opt.value] = true; }",
    "        for(const channel of channels) {",
    "          if(!existing[channel.channelSelector]) {",
    "            const o = document.createElement('option');",
    "            o.value = channel.channelSelector;",
    "            o.label = channel.name;",
    "            datalist.appendChild(o);",
    "          }",
    "        }",
    "      } catch(err) { console.warn('Channel selector suggestions failed to load.', err); }",
    "    })();",
    "  };",

    // Initialize disabled channel toggle, service filter, URL input listeners, and pending toast on page load.
    "  (() => {",

    // Show any toast queued by showToastAfterReload() before the last page reload.
    "    const pt = consumePendingToast();",
    "    if(pt) showToast(pt.message, pt.type);",
    "    if(safeStorageGet('prismcast-show-disabled-channels') === 'true') {",
    "      const table = document.querySelector('.channel-table');",
    "      const checkbox = document.getElementById('show-disabled-toggle');",
    "      if(table) table.classList.remove('hide-disabled');",
    "      if(checkbox) checkbox.checked = true;",
    "    }",

    // Set indeterminate state on scope toggle checkboxes. HTML has no indeterminate attribute — it must be set via JS on page load. The enabled and total values
    // are read from data attributes on the quick-action-count span, not from the display text — this decouples checkbox state from the text format.
    "    const scopeSpans = document.querySelectorAll('.quick-action-count[data-enabled][data-total]');",
    "    for(const span of scopeSpans) {",
    "      const enabled = parseInt(span.getAttribute('data-enabled'), 10);",
    "      const total = parseInt(span.getAttribute('data-total'), 10);",
    "      if((total > 0) && (enabled > 0) && (enabled < total)) {",
    "        const cb = document.querySelector('.scope-toggle[data-scope=\"' + span.getAttribute('data-scope') + '\"]');",
    "        if(cb) cb.indeterminate = true;",
    "      }",
    "    }",

    // Set indeterminate state on the HDHR bulk toggle if data-indeterminate is present.
    "    const hdhrToggle = document.getElementById('hdhr-bulk-toggle');",
    "    if(hdhrToggle && (hdhrToggle.getAttribute('data-indeterminate') === 'true')) hdhrToggle.indeterminate = true;",

    // Set indeterminate state on tag bulk toggle checkboxes. Same pattern as HDHR — HTML has no indeterminate attribute, so JS must set it on page load.
    "    const tagToggles = document.querySelectorAll('.tag-bulk-toggle[data-indeterminate=\"true\"]');",
    "    for(const tagToggle of tagToggles) tagToggle.indeterminate = true;",

    // Run channelTable.filter() on page load when a service filter is active. The server renders filtered options with the hidden attribute, but Safari ignores it on
    // option elements. This initial pass removes those options from the DOM to enforce the filter.
    "    const initFilterTags = channelTable.getEnabledFilterTags();",
    "    if(initFilterTags.length > 0) { channelTable.filter(initFilterTags); updateBulkAssignOptions(initFilterTags); }",
    "    const addUrlInput = document.getElementById('add-url');",
    "    if(addUrlInput) {",
    "      addUrlInput.addEventListener('input', () => {",
    "        updateSelectorSuggestions('add-url', 'add-selectorList');",

    // Deselect the active service pill if the user manually edits the URL. Check whether the current URL still matches the active pill's URL — if not, the
    // user has overridden the auto-fill and the pill should unhighlight. Also re-enable the profile dropdown since manual URL entry may need a custom profile.
    "        const activePill = document.querySelector('.provider-pill.active');",
    "        if(activePill && (activePill.getAttribute('data-url') !== addUrlInput.value)) {",
    "          activePill.classList.remove('active');",
    "          const profileSelect = document.getElementById('add-profile');",
    "          if(profileSelect) profileSelect.disabled = false;",
    "        }",

    // Check the entered URL against predefined channel domains. If the domain matches, show an inline hint suggesting the predefined channel. This extends the
    // form's existing URL-based intelligence (channelSelector suggestions, stationId auto-fill) with predefined channel awareness.
    "        const predefinedHint = document.getElementById('add-predefined-hint');",
    "        if(predefinedHint && (typeof predefinedByDomain !== 'undefined')) {",
    "          const parsedUrl = URL.parse(addUrlInput.value);",
    "          if(!parsedUrl) {",
    "            predefinedHint.style.display = 'none';",
    "          } else {",
    "            const urlHostname = parsedUrl.hostname;",
    "            const parts = urlHostname.split('.');",
    "            const conciseDomain = (parts.length > 2) ? parts.slice(-2).join('.') : urlHostname;",
    "            const matches = predefinedByDomain[conciseDomain];",
    "            if(matches && (matches.length > 0)) {",
    "              const names = matches.map((m) => '<strong>' + esc(m.name) + '</strong> (' + m.serviceCount + ' service' +",
    "                ((m.serviceCount === 1) ? '' : 's') + ')');",
    "              predefinedHint.innerHTML = names.join(', ') + ' available as predefined ' + ((matches.length === 1) ? 'channel' : 'channels') +",
    "                ' with multi-service support. <a href=\"#\" onclick=\"event.preventDefault(); openBrowseModal();\">Browse predefined channels</a>';",
    "              predefinedHint.style.display = '';",
    "            } else {",
    "              predefinedHint.style.display = 'none';",
    "            }",
    "          }",
    "        }",
    "      });",
    "      updateSelectorSuggestions('add-url', 'add-selectorList');",
    "    }",

    // Auto-fill station ID when the channelSelector matches a known entry with a stationId. Reads from the same channelSelectorsByDomain data used by the
    // datalist. The data-auto attribute tracks whether the current value was auto-filled — user edits clear it, preventing overwrites of intentional input.
    "    const addSelectorInput = document.getElementById('add-channelSelector');",
    "    const addStationInput = document.getElementById('add-stationId');",
    "    if(addSelectorInput && addStationInput) {",
    "      addStationInput.addEventListener('input', () => { addStationInput.removeAttribute('data-auto'); });",
    "      addSelectorInput.addEventListener('input', () => {",
    "        if(addStationInput.value && !addStationInput.hasAttribute('data-auto')) return;",
    "        const urlInput = document.getElementById('add-url');",
    "        if(!urlInput || !urlInput.value) return;",
    "        const parsed = URL.parse(urlInput.value);",
    "        if(!parsed) return;",
    "        const entries = (typeof channelSelectorsByDomain !== 'undefined') ? channelSelectorsByDomain[parsed.hostname] : null;",
    "        if(!entries) return;",
    "        const match = entries.find((e) => e.value === addSelectorInput.value);",
    "        if(match && match.stationId) { addStationInput.value = match.stationId; addStationInput.setAttribute('data-auto', '1'); }",
    "        else if(addStationInput.hasAttribute('data-auto')) { addStationInput.value = ''; addStationInput.removeAttribute('data-auto'); }",
    "      });",
    "    }",
    "  })();",

    // Login modal state tracking.
    "  let loginStatusInterval = null;",

    // Start login mode for a channel. Opens browser window and shows modal.
    "  window.startChannelLogin = async (channel) => {",
    "    try {",
    "      const res = await fetch('/auth/login', {",
    "        body: JSON.stringify({ channel }),",
    "        headers: { 'Content-Type': 'application/json' },",
    "        method: 'POST'",
    "      });",
    "      const result = await res.json();",
    "      if(result.success) {",
    "        showToast('Browser window opened. Complete authentication.', 'info');",
    "        showLoginModal();",
    "        startLoginStatusPolling();",
    "      } else {",
    "        showToast(extractErrorMessage(result, 'Failed to start login.'), 'error');",
    "      }",
    "    } catch(err) {",
    "      showToast('Failed to start login: ' + err.message, 'error');",
    "    }",
    "  };",

    // End login mode. Closes browser tab and hides modal.
    "  window.endLogin = async () => {",
    "    stopLoginStatusPolling();",
    "    try {",
    "      await fetch('/auth/done', { method: 'POST' });",
    "      hideLoginModal();",
    "      showToast('Authentication complete.', 'success');",
    "    } catch(err) {",
    "      showToast('Error ending login: ' + err.message, 'error');",
    "      hideLoginModal();",
    "    }",
    "  };",

    // Show the login modal.
    "  function showLoginModal() {",
    "    const modal = document.getElementById('login-modal');",
    "    if(modal) modal.style.display = 'flex';",
    "  }",

    // Hide the login modal.
    "  function hideLoginModal() {",
    "    const modal = document.getElementById('login-modal');",
    "    if(modal) modal.style.display = 'none';",
    "  }",

    // Start polling login status to detect when tab is closed externally. Errors are logged only on the first failure per polling session — a dead endpoint
    // would otherwise spam the console at 1Hz. The flag resets at each startLoginStatusPolling() call so subsequent sessions get a fresh log.
    "  function startLoginStatusPolling() {",
    "    stopLoginStatusPolling();",
    "    let errorLogged = false;",
    "    loginStatusInterval = setInterval(async () => {",
    "      try {",
    "        const res = await fetch('/auth/status');",
    "        const status = await res.json();",
    "        errorLogged = false;",
    "        if(!status.active) {",
    "          stopLoginStatusPolling();",
    "          hideLoginModal();",
    "          showToast('Login session ended.', 'info');",
    "        }",
    "      } catch(err) {",
    "        if(!errorLogged) { console.warn('Login status poll failed; suppressing further logs until next success.', err); errorLogged = true; }",
    "      }",
    "    }, 1000);",
    "  }",

    // Stop polling login status.
    "  function stopLoginStatusPolling() {",
    "    if(loginStatusInterval) {",
    "      clearInterval(loginStatusInterval);",
    "      loginStatusInterval = null;",
    "    }",
    "  }",

    // Attach validation and modified indicator handlers to form inputs.
    "  const form = document.getElementById('settings-form');",
    "  if(form) {",
    "    const inputs = form.querySelectorAll('input, select');",
    "    for(const input of inputs) {",
    "      const eventType = input.type === 'checkbox' ? 'change' : 'input';",
    "      input.addEventListener(eventType, function() {",
    "        validateInput(this);",
    "        updateModifiedIndicator(this);",
    "      });",
    "    }",

    // Wire up all checkboxes that have dependent fields. The updateDependentFields function is defined at the top level alongside the other helpers.
    "    const checkboxes = form.querySelectorAll('input[type=\"checkbox\"]');",
    "    for(const cb of checkboxes) {",
    "      cb.addEventListener('change', () => { updateDependentFields(cb.id); });",
    "    }",

    // Attach preset change handler to auto-fill bitrate and frame rate.
    "    const presetSelect = document.getElementById('streaming-qualityPreset');",
    "    if(presetSelect) {",
    "      presetSelect.addEventListener('change', function() { onPresetChange(this.value); });",
    "    }",
    "  }",

    // Checkbox list: collect checked values into the hidden input and update the modified indicator. Called by onchange on individual checkboxes within a
    // checkbox-list-grid. The hidden input holds the JSON-encoded array and participates in the standard form submission.
    "  window.updateCheckboxList = (checkbox) => {",
    "    const group = checkbox.closest('.form-group');",
    "    if(!group) return;",
    "    const hidden = group.querySelector('[data-checkbox-list]');",
    "    if(!hidden) return;",
    "    const grid = group.querySelector('.checkbox-list-grid');",
    "    if(!grid) return;",
    "    const cbs = grid.querySelectorAll('input[type=\"checkbox\"]');",
    "    const values = [];",
    "    for(const cb of cbs) {",
    "      if(cb.checked) values.push(cb.value);",
    "    }",
    "    hidden.value = JSON.stringify(values);",
    "    updateModifiedIndicator(hidden);",
    "  };",

    // Initialize subtab on load: hash > localStorage > default.
    "  initSubtab({",
    "    btnSelector: '.subtab-btn',",
    "    dataAttr: 'data-subtab',",
    "    hashVar: window.initialHashSubtab,",
    "    storageKey: 'prismcast-config-subtab',",
    "    switchFn: switchSubtab",
    "  });",

    "})();",
    "</script>"
  ].join("\n");
}
